import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { Gift } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CartDrawer from "@/components/CartDrawer";
import ProductCard from "@/components/ProductCard";
import ProductCardSkeleton from "@/components/ProductCardSkeleton";
import { supabase } from "@/integrations/supabase/client";
import { PRODUCT_CARD_SELECT, mapProductCard } from "@/lib/productCardData";

type Offer = { id: string; title_ar: string; subtitle_ar: string | null; description_ar: string | null; image_url: string | null; mobile_image_url: string | null; badge_text: string | null; cta_label: string | null; cta_url: string | null; discount_percentage: number | null; product_ids: string[] | null; apply_to_all: boolean | null; offer_type: string | null; start_date: string | null; end_date: string | null; sort_order: number | null };

const SeasonalOffersPage = () => {
  const { data: offers = [], isLoading } = useQuery({ queryKey: ["managed-offers"], queryFn: async () => { const { data, error } = await (supabase as any).from("offers").select("id,title_ar,subtitle_ar,description_ar,image_url,mobile_image_url,badge_text,cta_label,cta_url,discount_percentage,product_ids,apply_to_all,offer_type,start_date,end_date,sort_order").eq("is_active", true).order("sort_order", { ascending: true }); if (error) throw error; const now = Date.now(); return (data || []).filter((o: Offer) => (!o.start_date || new Date(o.start_date).getTime() <= now) && (!o.end_date || new Date(o.end_date).getTime() >= now)) as Offer[]; }, staleTime: 60_000 });
  const ids = useMemo(() => Array.from(new Set(offers.flatMap((o) => o.product_ids || []))), [offers]);
  const hasAll = offers.some((o) => o.apply_to_all);
  const { data: products = [], isLoading: productsLoading } = useQuery({ queryKey: ["managed-offer-products", ids.join(","), hasAll], enabled: offers.length > 0, queryFn: async () => { let query: any = supabase.from("products").select(PRODUCT_CARD_SELECT).eq("is_active", true); if (!hasAll && ids.length) query = query.in("id", ids); else if (!hasAll && !ids.length) return []; const { data, error } = await query.limit(120); if (error) throw error; const map = new Map((data || []).map((row: any) => [row.id, row])); const ordered = hasAll ? (data || []) : ids.map((id) => map.get(id)).filter(Boolean); return ordered.map((row: any) => mapProductCard(row)); }, staleTime: 60_000 });
  const hero = offers[0];
  const loading = isLoading || productsLoading;
  return <div className="min-h-screen bg-[#FFFDFC] text-[#302725]" dir="rtl"><Navbar /><CartDrawer /><main className="pb-16 md:pt-24">{hero && <section className="relative min-h-[250px] overflow-hidden bg-[#FFF3F1] md:min-h-[360px]">{hero.image_url && <picture>{hero.mobile_image_url && <source media="(max-width: 767px)" srcSet={hero.mobile_image_url} />}<img src={hero.image_url} alt={hero.title_ar} className="absolute inset-0 h-full w-full object-cover" /></picture>}<div className="absolute inset-0 bg-gradient-to-l from-[#FFF8F5]/95 via-[#FFF8F5]/75 to-transparent" /><div className="relative mx-auto flex min-h-[250px] max-w-[1400px] items-center px-5 md:min-h-[360px] md:px-8"><div className="max-w-lg">{hero.badge_text && <span className="text-[7px] tracking-[0.2em] text-[#B86168]">{hero.badge_text}</span>}<h1 className="mt-2 text-[28px] font-semibold text-[#403131] md:text-[42px]">{hero.title_ar}</h1>{hero.subtitle_ar && <p className="mt-2 text-[10px] leading-6 text-[#8C7772] md:text-[12px]">{hero.subtitle_ar}</p>}</div></div></section>}<section className="mx-auto w-full max-w-[1400px] px-3 py-7 md:px-6 md:py-10"><div className="mb-5 flex items-end justify-between"><div><div className="flex items-center gap-2"><span className="h-[2px] w-4 bg-[#D4777D]" /><span className="text-[7px] tracking-[0.2em] text-[#B86168]">FLAMINGO OFFERS</span></div><h2 className="mt-1 text-[19px] font-semibold">العروض المتاحة الآن</h2></div><span className="text-[9px] text-[#B86168]">{products.length} منتج</span></div>{loading ? <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <ProductCardSkeleton key={i} />)}</div> : offers.length === 0 ? <div className="flex min-h-[45vh] flex-col items-center justify-center text-center"><Gift className="h-7 w-7 text-[#C76D73]" /><h3 className="mt-4 text-[15px] font-semibold">لا توجد عروض نشطة حالياً</h3><p className="mt-1 text-[9px] text-muted-foreground">أي عرض تنشره من لوحة الإدارة سيظهر هنا تلقائياً.</p></div> : <div className="grid grid-cols-2 gap-x-2.5 gap-y-5 md:grid-cols-4 md:gap-5">{products.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div>}</section></main><Footer /></div>;
};

export default SeasonalOffersPage;
