-- Seed site_content keys for Products, Offers, and Reviews pages
-- Safe upsert: inserts missing keys and updates existing ones.

INSERT INTO public.site_content (key, title, content, content_ar, description)
VALUES
  -- Products page
  ('products_page_title', 'عنوان صفحة المنتجات', 'Season Collection', 'مجموعة الموسم', 'العنوان الافتراضي في هيرو صفحة المنتجات'),
  ('products_page_subtitle', 'وصف صفحة المنتجات', 'A clean catalog experience with practical filters.', 'تصميم متناسق مع بقية صفحات الموقع يركّز على وضوح العرض وسهولة الوصول للفلاتر.', 'الوصف الافتراضي أسفل عنوان صفحة المنتجات'),
  ('products_page_filter_cta', 'زر فتح الفلاتر', 'Start Filtering', 'ابدأ الفلترة', 'زر فتح درج الفلاتر في الهيرو'),
  ('products_page_reset_cta', 'زر تصفير الاختيارات', 'Reset Choices', 'تصفير الاختيارات', 'زر إعادة ضبط الفلاتر في الهيرو'),
  ('products_page_stat_products', 'تسمية إحصائية المنتجات', 'Products', 'المنتجات', 'تسمية عداد عدد المنتجات'),
  ('products_page_stat_filters', 'تسمية إحصائية الفلاتر', 'Filters', 'الفلاتر', 'تسمية عداد الفلاتر النشطة'),
  ('products_page_stat_page', 'تسمية إحصائية الصفحة', 'Page', 'الصفحة', 'تسمية رقم الصفحة الحالية'),
  ('products_page_hero_alt', 'النص البديل لصورة هيرو المنتجات', 'Featured visual', 'عرض خاص', 'النص البديل لصورة الهيرو عند عدم وجود فئة محددة'),
  ('products_page_chip_sale', 'شيب فلتر العروض', 'Sale', 'عروض', 'نص الشيب عند تفعيل فلتر العروض'),
  ('products_page_chip_stock', 'شيب فلتر المتوفر', 'In Stock', 'متوفر', 'نص الشيب عند تفعيل فلتر المتوفر'),
  ('products_page_count_label', 'تسمية عداد المنتجات', 'item', 'منتج', 'تسمية تظهر بجانب رقم عدد المنتجات الظاهرة'),
  ('products_page_empty_title', 'عنوان حالة عدم وجود منتجات', 'No products found', 'لم يتم العثور على منتجات', 'عنوان حالة عدم وجود نتائج'),
  ('products_page_empty_desc', 'وصف حالة عدم وجود منتجات', 'Try changing filters or explore curated collections.', 'غير الفلاتر أو استكشف مجموعاتنا المختارة.', 'وصف حالة عدم وجود نتائج'),
  ('products_page_empty_reset', 'زر إعادة التعيين في حالة عدم وجود نتائج', 'Reset', 'إعادة تعيين', 'زر لإعادة ضبط الفلاتر عند عدم وجود نتائج'),
  ('products_page_empty_cta', 'زر استكشاف الأقسام في حالة عدم وجود نتائج', 'Explore categories', 'استكشف الأقسام', 'زر للانتقال إلى الاستكشاف عند عدم وجود نتائج'),
  ('products_page_load_more', 'زر تحميل المزيد من المنتجات', 'Load more', 'عرض المزيد', 'زر تحميل الصفحة التالية من النتائج'),
  ('products_page_drawer_title', 'عنوان درج الفلاتر', 'Filter Products', 'فلترة المنتجات', 'عنوان واجهة الفلاتر الجانبية'),
  ('products_page_drawer_subtitle', 'وصف درج الفلاتر', 'Refine your selection to find the right item.', 'اختيار أدق للوصول للقطعة المناسبة', 'وصف قصير أسفل عنوان درج الفلاتر'),
  ('products_page_filter_category', 'عنوان قسم فلتر الفئة', 'Category', 'الفئة', 'عنوان مجموعة خيارات الفئات في الفلاتر'),
  ('products_page_filter_brand', 'عنوان قسم فلتر الماركة', 'Brand', 'الماركة', 'عنوان مجموعة خيارات الماركات في الفلاتر'),
  ('products_page_filter_color', 'عنوان قسم فلتر اللون', 'Color', 'اللون', 'عنوان مجموعة خيارات الألوان في الفلاتر'),
  ('products_page_filter_size', 'عنوان قسم فلتر المقاس', 'Size', 'المقاس', 'عنوان مجموعة خيارات المقاسات في الفلاتر'),
  ('products_page_filter_price', 'عنوان قسم فلتر السعر', 'Price', 'السعر', 'عنوان فلتر نطاق السعر'),
  ('products_page_filter_state', 'عنوان قسم فلتر الحالة', 'Status', 'الحالة', 'عنوان خيارات الحالة مثل العروض والمتوفر'),
  ('products_page_drawer_reset', 'زر إعادة تعيين درج الفلاتر', 'Reset', 'إعادة تعيين', 'زر إعادة ضبط الفلاتر داخل الدرج'),
  ('products_page_drawer_apply', 'زر تطبيق درج الفلاتر', 'Apply', 'تطبيق', 'زر إغلاق/تطبيق الفلاتر داخل الدرج'),
  ('products_page_quick_sizes', 'عنوان المقاسات في العرض السريع', 'Sizes', 'المقاسات', 'تسمية قسم المقاسات في نافذة العرض السريع'),
  ('products_page_quick_status_label', 'تسمية الحالة في العرض السريع', 'Status:', 'الحالة:', 'تسمية حالة التوفر في نافذة العرض السريع'),
  ('products_page_quick_status_available', 'قيمة متاح في العرض السريع', 'Available', 'متاح', 'نص حالة التوفر عند وجود مخزون'),
  ('products_page_quick_status_low', 'قيمة كمية قليلة في العرض السريع', 'Low stock', 'كمية قليلة', 'نص حالة التوفر عند انخفاض المخزون'),
  ('products_page_quick_status_unavailable', 'قيمة غير متوفر في العرض السريع', 'Out of stock', 'غير متوفر', 'نص حالة التوفر عند عدم وجود مخزون'),
  ('products_page_quick_add_to_cart', 'زر إضافة للسلة في العرض السريع', 'Add to cart', 'إضافة للسلة', 'زر الإضافة إلى السلة في نافذة العرض السريع'),

  -- Offers page
  ('offers_page_badge', 'شارة صفحة العروض', 'Limited-time offers', 'عروض محدودة المدة', 'الشارة الصغيرة أعلى هيرو صفحة العروض'),
  ('offers_page_subtitle', 'الوصف الافتراضي لصفحة العروض', 'Grab premium pieces at irresistible prices.', 'اغتنم الفرصة واحصل على أفخم القطع الذهبية بأسعار لا تُقاوم', 'وصف هيرو صفحة العروض عند غياب إعدادات العروض'),
  ('offers_page_countdown_label', 'تسمية عداد العروض', 'All offers end in', 'تنتهي جميع العروض خلال', 'النص الذي يسبق عداد الوقت الرئيسي'),
  ('offers_page_feature_1', 'ميزة 1 في صفحة العروض', 'Discounts up to 50%', 'خصومات تصل إلى 50%', 'نص الميزة الأولى أسفل الهيرو'),
  ('offers_page_feature_2', 'ميزة 2 في صفحة العروض', 'Free gifts', 'هدايا مجانية', 'نص الميزة الثانية أسفل الهيرو'),
  ('offers_page_feature_3', 'ميزة 3 في صفحة العروض', 'Fast shipping', 'شحن سريع', 'نص الميزة الثالثة أسفل الهيرو'),
  ('offers_page_loading', 'نص التحميل في صفحة العروض', 'Loading offers...', 'جاري تحميل العروض...', 'النص الظاهر أثناء تحميل بيانات العروض'),
  ('offers_page_expired_title', 'عنوان انتهاء العروض', 'Offers ended', 'انتهت العروض', 'عنوان حالة انتهاء العد التنازلي وعدم توفر عروض'),
  ('offers_page_expired_desc', 'وصف انتهاء العروض', 'Stay tuned for upcoming offers.', 'ترقبوا عروضنا القادمة! سنُعلمكم فور توفر عروض جديدة', 'وصف حالة انتهاء العروض'),
  ('offers_page_empty_title', 'عنوان عدم وجود عروض', 'No offers currently', 'لا توجد عروض حالياً', 'عنوان حالة عدم وجود عروض مفعلة'),
  ('offers_page_empty_desc', 'وصف عدم وجود عروض', 'Stay tuned for upcoming offers.', 'ترقبوا عروضنا القادمة! سنُعلمكم فور توفر عروض جديدة', 'وصف حالة عدم وجود عروض مفعلة'),

  -- Reviews page
  ('reviews_page_title', 'عنوان صفحة التقييمات', 'Customer Reviews', 'تقييمات العملاء', 'العنوان الرئيسي لصفحة التقييمات'),
  ('reviews_page_subtitle', 'وصف صفحة التقييمات', 'We value our customers opinions and strive to improve.', 'نفتخر بآراء عملائنا الكرام ونسعى دائماً لتقديم الأفضل', 'الوصف أسفل عنوان صفحة التقييمات'),
  ('reviews_page_stats_based_on', 'مقدمة إحصائية التقييمات', 'Based on', 'بناءً على', 'الكلمة التي تسبق عدد التقييمات في بطاقة الإحصاءات'),
  ('reviews_page_stats_reviews_word', 'اسم وحدة التقييم', 'reviews', 'تقييم', 'الكلمة التي تأتي بعد عدد التقييمات في بطاقة الإحصاءات'),
  ('reviews_page_form_title', 'عنوان نموذج إضافة تقييم', 'Add your review', 'أضف تقييمك', 'عنوان نموذج إرسال تقييم جديد'),
  ('reviews_page_form_rating_label', 'تسمية حقل التقييم', 'Rating', 'التقييم', 'عنوان اختيار النجوم'),
  ('reviews_page_form_name_label', 'تسمية حقل الاسم', 'Name', 'الاسم', 'عنوان حقل اسم العميل'),
  ('reviews_page_form_name_placeholder', 'نص مساعد حقل الاسم', 'Enter your name', 'أدخل اسمك', 'النص المساعد داخل حقل الاسم'),
  ('reviews_page_form_message_label', 'تسمية حقل الرسالة', 'Your review', 'تقييمك', 'عنوان حقل نص التقييم'),
  ('reviews_page_form_message_placeholder', 'نص مساعد حقل الرسالة', 'Share your experience with our products...', 'شاركنا تجربتك مع منتجاتنا...', 'النص المساعد داخل حقل نص التقييم'),
  ('reviews_page_form_submit', 'زر إرسال التقييم', 'Submit review', 'إرسال التقييم', 'نص زر إرسال نموذج التقييم'),
  ('reviews_page_list_title', 'عنوان قائمة التقييمات', 'All reviews', 'جميع التقييمات', 'عنوان قسم عرض التقييمات المعتمدة'),
  ('reviews_page_empty_title', 'عنوان عدم وجود تقييمات', 'No reviews yet', 'لا توجد تقييمات بعد', 'عنوان الحالة الفارغة لقائمة التقييمات'),
  ('reviews_page_empty_desc', 'وصف عدم وجود تقييمات', 'Be the first to review!', 'كن أول من يقيّم!', 'وصف الحالة الفارغة لقائمة التقييمات'),
  ('reviews_page_toast_success_title', 'عنوان رسالة نجاح التقييم', 'Thank you!', 'شكراً لك!', 'عنوان التنبيه بعد إرسال تقييم ناجح'),
  ('reviews_page_toast_success_desc', 'وصف رسالة نجاح التقييم', 'Your review has been submitted and will be reviewed soon.', 'تم إرسال تقييمك وسيتم مراجعته قريباً', 'وصف التنبيه بعد إرسال تقييم ناجح'),
  ('reviews_page_toast_error_title', 'عنوان رسالة خطأ التقييم', 'Error', 'خطأ', 'عنوان التنبيه عند فشل إرسال التقييم'),
  ('reviews_page_toast_error_desc', 'وصف رسالة خطأ التقييم', 'An error occurred while submitting your review.', 'حدث خطأ أثناء إرسال التقييم', 'وصف التنبيه عند فشل إرسال التقييم'),
  ('reviews_page_toast_warning_title', 'عنوان رسالة تنبيه التقييم', 'Notice', 'تنبيه', 'عنوان تنبيه الحقول الناقصة في نموذج التقييم'),
  ('reviews_page_toast_warning_desc', 'وصف رسالة تنبيه التقييم', 'Please fill in all fields.', 'يرجى ملء جميع الحقول', 'وصف تنبيه الحقول الناقصة في نموذج التقييم')
ON CONFLICT (key) DO UPDATE
SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  content_ar = EXCLUDED.content_ar,
  description = EXCLUDED.description,
  updated_at = now();
