import { useMemo, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { toast } from "@/hooks/use-toast";
import { uploadOptimizedImage } from "@/lib/prepareImageUpload";
import { ArrowRight, CheckCircle2, ChevronDown, ChevronUp, CircleOff, Image as ImageIcon, Layers3, Loader2, Package, Pencil, Plus, Search, Trash2, Upload, X, type LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";

interface Section {
  id: string;
  brand_id: string | null;
  brand_page_id: string;
  name: string;
  slug: string;
  image_url: string | null;
  description: string | null;
  sort_order: number | null;
  is_active: boolean | null;
  category_name?: string | null;
}

interface BrandOpt {
  id: string;
  name: string;
  slug: string | null;
  logo_url: string | null;
  hero_image: string | null;
  is_active: boolean | null;
}

interface BrandPageRow {
  id: string;
  brand_id: string;
}

interface SectionProductLink {
  section_id: string;
}

type SectionForm = {
  name: string;
  slug: string;
  image_url: string;
  description: string;
  sort_order: number;
  is_active: boolean;
};

const emptyForm = (sortOrder = 0): SectionForm => ({
  name: "",
  slug: "",
  image_url: "",
  description: "",
  sort_order: sortOrder,
  is_active: true,
});

const slugify = (value: string) => value.toLowerCase().trim().replace(/[^\w\u0600-\u06FF]+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "");

const AdminBrandSectionsPage = () => {
  const { id: routeBrandId } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [selectedBrandId, setSelectedBrandId] = useState<string | undefined>(routeBrandId);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<Section | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Section | null>(null);
  const [form, setForm] = useState<SectionForm>(emptyForm());
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [movingId, setMovingId] = useState<string | null>(null);
  const [search, setSearch] = useState("");

  /* =========================================================
     BRANDS
  ========================================================= */

  const { data: brands = [], isLoading: brandsLoading } = useQuery({
    queryKey: ["all-brands-for-sections"],
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brands").select("id,name,slug,logo_url,hero_image,is_active").order("sort_order", { ascending: true }).order("name", { ascending: true });

      if (error) throw error;

      return (data || []) as BrandOpt[];
    },
    staleTime: 60_000,
  });

  const activeBrandId = selectedBrandId || brands[0]?.id || "";
  const activeBrand = useMemo(() => brands.find((brand) => brand.id === activeBrandId) || null, [brands, activeBrandId]);

  /* =========================================================
     BRAND PAGE
  ========================================================= */

  const { data: brandPage = null, isLoading: brandPageLoading } = useQuery({
    queryKey: ["brand-page-id-for-sections", activeBrandId],
    enabled: Boolean(activeBrandId),
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brand_pages").select("id,brand_id").eq("brand_id", activeBrandId).maybeSingle();

      if (error) throw error;

      return (data || null) as BrandPageRow | null;
    },
    staleTime: 30_000,
  });

  /* =========================================================
     SECTIONS
  ========================================================= */

  const { data: sections = [], isLoading, isFetching } = useQuery({
    queryKey: ["brand-sections-admin", activeBrandId],
    enabled: Boolean(activeBrandId),
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brand_sections").select("id,brand_id,brand_page_id,name,slug,image_url,description,sort_order,is_active,category_name").eq("brand_id", activeBrandId).order("sort_order", { ascending: true }).order("name", { ascending: true });

      if (error) throw error;

      return (data || []) as Section[];
    },
    staleTime: 20_000,
  });

  const sectionIds = useMemo(() => sections.map((section) => section.id), [sections]);

  const { data: productLinks = [] } = useQuery({
    queryKey: ["brand-section-product-counts", sectionIds],
    enabled: sectionIds.length > 0,
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brand_section_products").select("section_id").in("section_id", sectionIds);

      if (error) throw error;

      return (data || []) as SectionProductLink[];
    },
    staleTime: 20_000,
  });

  const productCounts = useMemo(() => {
    return productLinks.reduce<Record<string, number>>((accumulator, row) => {
      accumulator[row.section_id] = (accumulator[row.section_id] || 0) + 1;
      return accumulator;
    }, {});
  }, [productLinks]);

  const stats = useMemo(() => {
    const active = sections.filter((section) => section.is_active).length;
    const withProducts = sections.filter((section) => (productCounts[section.id] || 0) > 0).length;
    const withImages = sections.filter((section) => Boolean(section.image_url)).length;

    return {
      total: sections.length,
      active,
      inactive: sections.length - active,
      withProducts,
      withImages,
    };
  }, [sections, productCounts]);

  const filteredSections = useMemo(() => {
    const query = search.trim().toLowerCase();

    if (!query) return sections;

    return sections.filter((section) => section.name.toLowerCase().includes(query) || section.slug.toLowerCase().includes(query) || String(section.description || "").toLowerCase().includes(query));
  }, [sections, search]);

  /* =========================================================
     FORM
  ========================================================= */

  const resetForm = () => {
    setForm(emptyForm(sections.length));
    setEditing(null);
    setSlugAutoGenerated(true);
    setDialogOpen(false);
  };

  const openNew = () => {
    setEditing(null);
    setSlugAutoGenerated(true);
    setForm(emptyForm(sections.length));
    setDialogOpen(true);
  };

  const openEdit = (section: Section) => {
    setEditing(section);
    setSlugAutoGenerated(false);
    setForm({
      name: section.name,
      slug: section.slug,
      image_url: section.image_url || "",
      description: section.description || "",
      sort_order: section.sort_order ?? 0,
      is_active: section.is_active ?? true,
    });
    setDialogOpen(true);
  };

  const handleNameChange = (name: string) => {
    setForm((current) => ({
      ...current,
      name,
      slug: slugAutoGenerated ? slugify(name) : current.slug,
    }));
  };

  const handleSlugChange = (slug: string) => {
    setSlugAutoGenerated(false);
    setForm((current) => ({ ...current, slug: slugify(slug) }));
  };

  /* =========================================================
     IMAGE
  ========================================================= */

  const upload = async (file: File) => {
    if (!file.type.startsWith("image/") && !/\.(heic|heif)$/i.test(file.name)) {
      toast({ title: "ملف غير صالح", description: "اختر صورة صحيحة.", variant: "destructive" });
      return;
    }

    if (file.size > 12 * 1024 * 1024) {
      toast({ title: "الصورة كبيرة جدًا", description: "الحد الأقصى المسموح 12MB.", variant: "destructive" });
      return;
    }

    setUploading(true);

    try {
      const imageUrl = await uploadOptimizedImage(file, "brands/sections", { maxSizeMB: 0.8, maxWidthOrHeight: 1400 });

      setForm((current) => ({ ...current, image_url: imageUrl }));

      toast({ title: "تم رفع الصورة" });
    } catch (error: any) {
      toast({ title: "فشل رفع الصورة", description: error?.message || "تعذر رفع الصورة.", variant: "destructive" });
    } finally {
      setUploading(false);
    }
  };

  const handleImageInput = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];

    if (file) void upload(file);

    event.target.value = "";
  };

  /* =========================================================
     SAVE
  ========================================================= */

  const save = useMutation({
    mutationFn: async () => {
      if (!activeBrandId) throw new Error("اختر ماركة أولًا.");

      const name = form.name.trim();
      const slug = slugify(form.slug || name);

      if (!name) throw new Error("اسم القسم مطلوب.");
      if (!slug) throw new Error("تعذر إنشاء رابط صالح للقسم.");

      let brandPageId = brandPage?.id || "";

      if (!brandPageId) {
        const { data: createdPage, error: createPageError } = await (supabase as any).from("brand_pages").upsert({
          brand_id: activeBrandId,
          title: activeBrand?.name || null,
          description: null,
          hero_image: activeBrand?.hero_image || null,
          is_active: true,
        }, { onConflict: "brand_id" }).select("id").single();

        if (createPageError) throw createPageError;

        brandPageId = createdPage.id;
      }

      let duplicateQuery = (supabase as any).from("brand_sections").select("id").eq("brand_id", activeBrandId).eq("slug", slug).limit(1);

      if (editing) duplicateQuery = duplicateQuery.neq("id", editing.id);

      const { data: duplicated, error: duplicateError } = await duplicateQuery;

      if (duplicateError) throw duplicateError;

      if ((duplicated || []).length > 0) throw new Error(`الرابط "${slug}" مستخدم في قسم آخر لهذه الماركة.`);

      const payload = {
        brand_id: activeBrandId,
        brand_page_id: brandPageId,
        name,
        slug,
        image_url: form.image_url || null,
        description: form.description.trim() || null,
        sort_order: Math.max(0, Number(form.sort_order || 0)),
        is_active: form.is_active,
      };

      if (editing) {
        const { error } = await (supabase as any).from("brand_sections").update(payload).eq("id", editing.id);
        if (error) throw error;
        return;
      }

      const { error } = await (supabase as any).from("brand_sections").insert(payload);
      if (error) throw error;
    },

    onSuccess: async () => {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["brand-sections-admin", activeBrandId] }),
        queryClient.invalidateQueries({ queryKey: ["brand-page-id-for-sections", activeBrandId] }),
        queryClient.invalidateQueries({ queryKey: ["admin-brand-pages"] }),
        queryClient.invalidateQueries({ queryKey: ["brand-page-sections"] }),
      ]);

      toast({ title: editing ? "تم تحديث القسم" : "تمت إضافة القسم" });

      resetForm();
    },

    onError: (error: any) => {
      toast({
        title: "تعذر حفظ القسم",
        description: error?.message || "حدث خطأ أثناء الحفظ.",
        variant: "destructive",
      });
    },
  });

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    save.mutate();
  };

  /* =========================================================
     ACTIVE
  ========================================================= */

  const toggleActiveMutation = useMutation({
    mutationFn: async ({ id, is_active }: { id: string; is_active: boolean }) => {
      const { error } = await (supabase as any).from("brand_sections").update({ is_active }).eq("id", id);

      if (error) throw error;

      return { id, is_active };
    },

    onMutate: async ({ id, is_active }) => {
      await queryClient.cancelQueries({ queryKey: ["brand-sections-admin", activeBrandId] });

      const previous = queryClient.getQueryData<Section[]>(["brand-sections-admin", activeBrandId]);

      queryClient.setQueryData<Section[]>(["brand-sections-admin", activeBrandId], (current = []) => current.map((section) => section.id === id ? { ...section, is_active } : section));

      return { previous };
    },

    onError: (error: any, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(["brand-sections-admin", activeBrandId], context.previous);

      toast({
        title: "تعذر تحديث الحالة",
        description: error?.message || "حدث خطأ.",
        variant: "destructive",
      });
    },

    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ["brand-sections-admin", activeBrandId] });
    },
  });

  /* =========================================================
     ORDER
  ========================================================= */

  const moveSection = async (section: Section, direction: "up" | "down") => {
    const index = sections.findIndex((item) => item.id === section.id);
    if (index < 0) return;

    const newIndex = direction === "up" ? index - 1 : index + 1;
    if (newIndex < 0 || newIndex >= sections.length) return;

    const previous = [...sections];
    const reordered = [...sections];
    const current = reordered[index];

    reordered[index] = reordered[newIndex];
    reordered[newIndex] = current;

    const normalized = reordered.map((item, itemIndex) => ({ ...item, sort_order: itemIndex }));

    setMovingId(section.id);
    queryClient.setQueryData(["brand-sections-admin", activeBrandId], normalized);

    try {
      const results = await Promise.all(normalized.map((item) => (supabase as any).from("brand_sections").update({ sort_order: item.sort_order }).eq("id", item.id)));
      const failed = results.find((result) => result.error);

      if (failed?.error) throw failed.error;

      toast({ title: "تم تحديث ترتيب الأقسام" });
    } catch (error: any) {
      queryClient.setQueryData(["brand-sections-admin", activeBrandId], previous);

      toast({
        title: "تعذر تحديث الترتيب",
        description: error?.message || "حدث خطأ.",
        variant: "destructive",
      });
    } finally {
      setMovingId(null);
    }
  };

  /* =========================================================
     DELETE
  ========================================================= */

  const del = useMutation({
    mutationFn: async (section: Section) => {
      const { error } = await (supabase as any).from("brand_sections").delete().eq("id", section.id);

      if (error) throw error;
    },

    onSuccess: async () => {
      setDeleteTarget(null);

      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["brand-sections-admin", activeBrandId] }),
        queryClient.invalidateQueries({ queryKey: ["brand-section-product-counts"] }),
        queryClient.invalidateQueries({ queryKey: ["brand-page-sections"] }),
      ]);

      toast({ title: "تم حذف القسم" });
    },

    onError: (error: any) => {
      toast({
        title: "تعذر حذف القسم",
        description: error?.message || "حدث خطأ أثناء الحذف.",
        variant: "destructive",
      });
    },
  });

  /* =========================================================
     RENDER
  ========================================================= */

  return (
    <div className="w-full space-y-4" dir="rtl">
      <AdminPageHeader category="الماركات" title="أقسام الماركة" description={activeBrand ? `إدارة أقسام ${activeBrand.name} والمنتجات المرتبطة بها` : "إدارة أقسام صفحات الماركات"} actions={[{ label: "رجوع", icon: ArrowRight, onClick: () => navigate("/admin/brand-pages"), variant: "secondary" }, { label: "إضافة قسم", icon: Plus, onClick: openNew, variant: "primary" }]} />

      <section className="grid grid-cols-2 gap-[9px] lg:grid-cols-4">
        <SectionStatCard title="إجمالي الأقسام" value={stats.total} helper={activeBrand?.name || "الماركة الحالية"} icon={Layers3} tone="indigo" />
        <SectionStatCard title="الأقسام النشطة" value={stats.active} helper={`${stats.inactive} قسم معطل`} icon={CheckCircle2} tone="green" />
        <SectionStatCard title="بها منتجات" value={stats.withProducts} helper="مرتبطة بمنتجات فعلية" icon={Package} tone="blue" />
        <SectionStatCard title="بها صور" value={stats.withImages} helper={`${stats.total - stats.withImages} بدون صورة`} icon={ImageIcon} tone="coral" />
      </section>

      <section className="overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white">
        <div className="flex items-center justify-between border-b border-[#EDF0F3] px-[13px] py-[10px]">
          <div>
            <h2 className="text-[11px] font-semibold text-[#444B55]">الماركة والبحث</h2>
            <p className="mt-[3px] text-[8px] text-[#9BA2AC]">اختر الماركة ثم ابحث داخل أقسامها</p>
          </div>

          {search && (
            <button type="button" onClick={() => setSearch("")} className="flex h-[30px] items-center gap-[5px] rounded-[8px] px-[8px] text-[8px] font-semibold text-[#7E8690] hover:bg-[#F7F8FA]">
              <X className="h-[10px] w-[10px]" />
              مسح البحث
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 gap-[7px] p-[11px] lg:grid-cols-[250px_minmax(0,1fr)]">
          <Select value={activeBrandId} onValueChange={setSelectedBrandId} disabled={brandsLoading}>
            <SelectTrigger className="h-[40px] rounded-[9px] border-[#E3E7EC] bg-[#F8FAFC] text-[9px] shadow-none focus:ring-0">
              <SelectValue placeholder="اختر ماركة" />
            </SelectTrigger>

            <SelectContent>
              {brands.map((brand) => (
                <SelectItem key={brand.id} value={brand.id}>{brand.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>

          <div className="relative">
            <Search className="pointer-events-none absolute right-[12px] top-1/2 h-[13px] w-[13px] -translate-y-1/2 text-[#969EA8]" />
            <Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث باسم القسم أو الرابط..." className="h-[40px] rounded-[9px] border-[#E3E7EC] bg-[#F8FAFC] pr-[35px] text-[10px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
          </div>
        </div>
      </section>

      {!brandPageLoading && activeBrandId && !brandPage && (
        <section className="rounded-[12px] border border-[#DCE7F4] bg-[#F5F8FC] px-[11px] py-[9px]">
          <p className="text-[8px] font-semibold text-[#526B89]">هذه الماركة لا تحتوي صفحة ماركة بعد</p>
          <p className="mt-[3px] text-[7px] leading-5 text-[#7F8FA2]">عند إضافة أول قسم سيتم إنشاء صفحة الماركة تلقائيًا وربط القسم بها، ولن يفشل الحفظ بسبب عدم وجود brand_page.</p>
        </section>
      )}

      <section className="hidden overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white md:block">
        <div className="flex items-center justify-between border-b border-[#EAEDF1] px-[13px] py-[10px]">
          <div>
            <h2 className="text-[11px] font-semibold text-[#454C56]">أقسام {activeBrand?.name || "الماركة"}</h2>
            <p className="mt-[3px] text-[8px] text-[#9CA3AC]">{filteredSections.length.toLocaleString("ar-EG")} قسم ظاهر في القائمة</p>
          </div>

          {isFetching && (
            <span className="flex items-center gap-[5px] text-[8px] text-[#969DA7]">
              <Loader2 className="h-[10px] w-[10px] animate-spin" />
              تحديث...
            </span>
          )}
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1040px]">
            <thead>
              <tr className="h-[42px] border-b border-[#EAEDF1] bg-[#FAFBFC] text-[9px] font-semibold text-[#858D97]">
                <th className="w-[68px] px-[10px] text-center">الترتيب</th>
                <th className="w-[76px] px-[10px] text-right">الصورة</th>
                <th className="px-[12px] text-right">القسم</th>
                <th className="px-[12px] text-right">الرابط</th>
                <th className="px-[12px] text-right">المنتجات</th>
                <th className="px-[12px] text-right">الحالة</th>
                <th className="w-[170px] px-[12px] text-center">الإجراءات</th>
              </tr>
            </thead>

            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan={7} className="h-[260px] text-center">
                    <Loader2 className="mx-auto h-[20px] w-[20px] animate-spin text-[#675CBA]" />
                  </td>
                </tr>
              ) : filteredSections.length === 0 ? (
                <tr>
                  <td colSpan={7}>
                    <EmptySections />
                  </td>
                </tr>
              ) : (
                filteredSections.map((section) => {
                  const index = sections.findIndex((item) => item.id === section.id);
                  const productsCount = productCounts[section.id] || 0;

                  return (
                    <tr key={section.id} className="h-[68px] border-b border-[#F0F2F5] transition-colors last:border-b-0 hover:bg-[#FCFDFE]">
                      <td className="px-[10px]">
                        <div className="flex items-center justify-center gap-[2px]">
                          <div className="flex flex-col">
                            <button type="button" disabled={index <= 0 || Boolean(movingId)} onClick={() => void moveSection(section, "up")} className="flex h-[20px] w-[24px] items-center justify-center rounded-[6px] text-[#8D949E] hover:bg-[#F1F3F6] disabled:opacity-25"><ChevronUp className="h-[9px] w-[9px]" /></button>
                            <button type="button" disabled={index >= sections.length - 1 || Boolean(movingId)} onClick={() => void moveSection(section, "down")} className="flex h-[20px] w-[24px] items-center justify-center rounded-[6px] text-[#8D949E] hover:bg-[#F1F3F6] disabled:opacity-25"><ChevronDown className="h-[9px] w-[9px]" /></button>
                          </div>

                          <span className="text-[7px] font-semibold text-[#9BA2AC]">{movingId === section.id ? <Loader2 className="h-[9px] w-[9px] animate-spin" /> : index + 1}</span>
                        </div>
                      </td>

                      <td className="px-[10px]">
                        <SectionImage section={section} />
                      </td>

                      <td className="px-[12px]">
                        <div className="min-w-[200px]">
                          <p className="max-w-[240px] truncate text-[10.5px] font-semibold text-[#414953]">{section.name}</p>
                          {section.description && <p className="mt-[4px] max-w-[260px] truncate text-[7px] text-[#9BA2AC]">{section.description}</p>}
                        </div>
                      </td>

                      <td className="px-[12px]">
                        <span dir="ltr" className="block max-w-[190px] truncate text-right text-[8px] font-medium text-[#737C87]">/{section.slug}</span>
                      </td>

                      <td className="px-[12px]">
                        <span className={cn("inline-flex h-[25px] items-center gap-[5px] rounded-[7px] border px-[7px] text-[6.5px] font-semibold", productsCount > 0 ? "border-[#DCE7F4] bg-[#F1F6FC] text-[#5679A4]" : "border-[#E4E7EB] bg-[#F5F6F8] text-[#858D97]")}>
                          <Package className="h-[8px] w-[8px]" />
                          {productsCount} منتج
                        </span>
                      </td>

                      <td className="px-[12px]">
                        <div className="flex items-center gap-[8px]">
                          <Switch checked={section.is_active ?? true} onCheckedChange={(checked) => toggleActiveMutation.mutate({ id: section.id, is_active: checked })} />
                          <SectionStatus active={Boolean(section.is_active)} />
                        </div>
                      </td>

                      <td className="px-[12px]">
                        <div className="flex items-center justify-center gap-[4px]">
                          <button type="button" onClick={() => openEdit(section)} className="flex h-[30px] items-center justify-center gap-[5px] rounded-[8px] border border-[#E2DEF3] bg-white px-[8px] text-[7px] font-semibold text-[#675CBA] hover:bg-[#F5F3FF]"><Pencil className="h-[9px] w-[9px]" />تعديل</button>
                          <button type="button" onClick={() => navigate(`/admin/brand-sections/${section.id}/products`)} className="flex h-[30px] items-center justify-center gap-[5px] rounded-[8px] border border-[#DCE7F4] bg-white px-[8px] text-[7px] font-semibold text-[#5680CF] hover:bg-[#F3F7FC]"><Package className="h-[9px] w-[9px]" />المنتجات</button>
                          <button type="button" onClick={() => setDeleteTarget(section)} className="flex h-[30px] w-[30px] items-center justify-center rounded-[8px] border border-[#F0D7D4] bg-white text-[#C15F56] hover:bg-[#FFF3F1]"><Trash2 className="h-[10px] w-[10px]" /></button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-[8px] md:hidden">
        {isLoading ? (
          <div className="flex h-[220px] items-center justify-center rounded-[14px] border border-[#E5E9EF] bg-white"><Loader2 className="h-[20px] w-[20px] animate-spin text-[#675CBA]" /></div>
        ) : filteredSections.length === 0 ? (
          <EmptySections />
        ) : (
          filteredSections.map((section) => {
            const index = sections.findIndex((item) => item.id === section.id);
            const productsCount = productCounts[section.id] || 0;

            return (
              <article key={section.id} className="overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white">
                <div className="p-[11px]">
                  <div className="flex gap-[10px]">
                    <SectionImage section={section} mobile />

                    <div className="min-w-0 flex-1">
                      <div className="flex items-start justify-between gap-[7px]">
                        <div className="min-w-0">
                          <h3 className="truncate text-[11px] font-semibold text-[#3B424C]">{section.name}</h3>
                          <p dir="ltr" className="mt-[3px] truncate text-right text-[7px] text-[#9299A3]">/{section.slug}</p>
                        </div>
                        <SectionStatus active={Boolean(section.is_active)} />
                      </div>

                      <div className="mt-[8px] flex flex-wrap gap-[5px]">
                        <span className="rounded-[6px] bg-[#EDF4FF] px-[7px] py-[4px] text-[7px] font-semibold text-[#567BC5]">{productsCount} منتج</span>
                        <span className="rounded-[6px] bg-[#F2F4F7] px-[7px] py-[4px] text-[7px] font-semibold text-[#757D87]">الترتيب #{index + 1}</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-[38px_38px_1fr_1fr_42px] gap-[5px] border-t border-[#EDF0F3] bg-[#FAFBFC] p-[7px]">
                  <button type="button" disabled={index <= 0 || Boolean(movingId)} onClick={() => void moveSection(section, "up")} className="flex h-[35px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[#7C848E] disabled:opacity-30"><ChevronUp className="h-[10px] w-[10px]" /></button>
                  <button type="button" disabled={index >= sections.length - 1 || Boolean(movingId)} onClick={() => void moveSection(section, "down")} className="flex h-[35px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[#7C848E] disabled:opacity-30"><ChevronDown className="h-[10px] w-[10px]" /></button>
                  <button type="button" onClick={() => openEdit(section)} className="flex h-[35px] items-center justify-center gap-[5px] rounded-[8px] border border-[#E2DEF3] bg-white text-[8px] font-semibold text-[#675CBA]"><Pencil className="h-[10px] w-[10px]" />تعديل</button>
                  <button type="button" onClick={() => navigate(`/admin/brand-sections/${section.id}/products`)} className="flex h-[35px] items-center justify-center gap-[5px] rounded-[8px] border border-[#DCE7F4] bg-white text-[8px] font-semibold text-[#5680CF]"><Package className="h-[10px] w-[10px]" />المنتجات</button>
                  <button type="button" onClick={() => setDeleteTarget(section)} className="flex h-[35px] w-[42px] items-center justify-center rounded-[8px] border border-[#F0D7D4] bg-white text-[#C15F56]"><Trash2 className="h-[11px] w-[11px]" /></button>
                </div>
              </article>
            );
          })
        )}
      </section>

      <Dialog open={dialogOpen} onOpenChange={(open) => { if (!open && !save.isPending && !uploading) resetForm(); else if (open) setDialogOpen(true); }}>
        <DialogContent dir="rtl" className="max-h-[92vh] max-w-[700px] overflow-y-auto rounded-[18px] border-[#E4E8ED] bg-[#F7F8FA] p-0">
          <DialogHeader className="sticky top-0 z-20 border-b border-[#E6E9EE] bg-white px-5 py-4">
            <div className="flex items-center gap-[10px]">
              <div className="flex h-[36px] w-[36px] items-center justify-center rounded-[11px] bg-[#F1EFFF] text-[#675CBA]">{editing ? <Pencil className="h-[15px] w-[15px]" /> : <Plus className="h-[15px] w-[15px]" />}</div>
              <div>
                <DialogTitle className="text-right text-[14px] font-semibold text-[#343B45]">{editing ? "تعديل القسم" : "إضافة قسم جديد"}</DialogTitle>
                <DialogDescription className="mt-[3px] text-right text-[8px] text-[#9299A3]">إدارة اسم القسم وصورته ورابطه وحالة ظهوره داخل صفحة الماركة.</DialogDescription>
              </div>
            </div>
          </DialogHeader>

          <form onSubmit={handleSubmit}>
            <div className="grid grid-cols-1 gap-[10px] p-[10px] lg:grid-cols-[minmax(0,1fr)_240px]">
              <div className="space-y-[10px]">
                <FormSection title="بيانات القسم" icon={Layers3}>
                  <Field label="اسم القسم" required>
                    <Input value={form.name} onChange={(event) => handleNameChange(event.target.value)} placeholder="مثال: ساعات نسائية" className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9.5px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                  </Field>

                  <Field label="الرابط">
                    <Input value={form.slug} placeholder={slugify(form.name) || "section-slug"} onChange={(event) => handleSlugChange(event.target.value)} dir="ltr" className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                  </Field>

                  <Field label="الوصف">
                    <Textarea rows={5} value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} placeholder="وصف مختصر للقسم..." className="resize-none rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] leading-5 shadow-none focus-visible:bg-white focus-visible:ring-0" />
                  </Field>
                </FormSection>

                <FormSection title="العرض والترتيب" icon={CheckCircle2}>
                  <div className="grid grid-cols-1 gap-[8px] sm:grid-cols-2">
                    <Field label="ترتيب العرض">
                      <Input type="number" min={0} value={form.sort_order} onChange={(event) => setForm((current) => ({ ...current, sort_order: Number.parseInt(event.target.value, 10) || 0 }))} className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                    </Field>

                    <div className="flex min-h-[64px] items-center justify-between rounded-[10px] border border-[#E6E9EE] bg-[#FAFBFC] px-[10px]">
                      <div>
                        <p className="text-[8.5px] font-semibold text-[#555D67]">حالة القسم</p>
                        <p className="mt-[2px] text-[6.5px] text-[#9BA2AC]">{form.is_active ? "ظاهر للعملاء" : "مخفي"}</p>
                      </div>
                      <Switch checked={form.is_active} onCheckedChange={(value) => setForm((current) => ({ ...current, is_active: value }))} />
                    </div>
                  </div>
                </FormSection>
              </div>

              <div className="lg:sticky lg:top-[84px] lg:self-start">
                <FormSection title="صورة القسم" icon={ImageIcon}>
                  {form.image_url ? (
                    <div className="space-y-[7px]">
                      <div className="relative aspect-square overflow-hidden rounded-[11px] border border-[#E3E7EC] bg-[#F5F6F8]">
                        <img src={form.image_url} alt="" loading="lazy" className="h-full w-full object-cover" />
                        <button type="button" onClick={() => setForm((current) => ({ ...current, image_url: "" }))} className="absolute left-[7px] top-[7px] flex h-[27px] w-[27px] items-center justify-center rounded-[8px] bg-white/95 text-[#C15F56] shadow-sm"><Trash2 className="h-[10px] w-[10px]" /></button>
                      </div>

                      <label className="flex h-[34px] cursor-pointer items-center justify-center gap-[5px] rounded-[8px] border border-[#E2E6EB] bg-white text-[7.5px] font-semibold text-[#6F7781] hover:bg-[#F8FAFC]">
                        {uploading ? <Loader2 className="h-[10px] w-[10px] animate-spin" /> : <Upload className="h-[10px] w-[10px]" />}
                        تغيير الصورة
                        <input type="file" accept="image/*,.heic,.heif" className="hidden" disabled={uploading} onChange={handleImageInput} />
                      </label>
                    </div>
                  ) : (
                    <label className={cn("flex aspect-square cursor-pointer flex-col items-center justify-center rounded-[11px] border border-dashed border-[#D9DEE5] bg-[#FAFBFC] hover:border-[#BFB8DE] hover:bg-[#F9F8FF]", uploading && "pointer-events-none opacity-60")}>
                      {uploading ? <Loader2 className="h-[18px] w-[18px] animate-spin text-[#675CBA]" /> : <><div className="flex h-[36px] w-[36px] items-center justify-center rounded-[10px] bg-[#F1EFFF] text-[#675CBA]"><Upload className="h-[14px] w-[14px]" /></div><span className="mt-[7px] text-[7.5px] font-semibold text-[#626A74]">رفع صورة القسم</span><span className="mt-[2px] text-[6px] text-[#A0A6AF]">JPG · PNG · WEBP · HEIC</span></>}
                      <input type="file" accept="image/*,.heic,.heif" className="hidden" disabled={uploading} onChange={handleImageInput} />
                    </label>
                  )}
                </FormSection>
              </div>
            </div>

            <div className="sticky bottom-0 z-20 flex items-center justify-end gap-[7px] border-t border-[#E5E9EF] bg-white px-5 py-3">
              <Button type="button" variant="outline" disabled={save.isPending || uploading} onClick={resetForm} className="h-[36px] rounded-[9px] border-[#E1E5EA] bg-white px-4 text-[8px] font-semibold text-[#707883] shadow-none">إلغاء</Button>
              <Button type="submit" disabled={save.isPending || uploading || !activeBrandId} className="h-[36px] rounded-[9px] bg-[#675CBA] px-5 text-[8px] font-semibold text-white shadow-none hover:bg-[#594FAB]">{save.isPending ? <Loader2 className="ml-[5px] h-[11px] w-[11px] animate-spin" /> : editing ? <Pencil className="ml-[5px] h-[11px] w-[11px]" /> : <Plus className="ml-[5px] h-[11px] w-[11px]" />}{editing ? "حفظ التعديلات" : "إضافة القسم"}</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null); }}>
        <AlertDialogContent dir="rtl" className="max-w-[420px] rounded-[15px] border-[#E4E8ED] bg-white p-5">
          <AlertDialogHeader>
            <div className="mb-2 flex h-[38px] w-[38px] items-center justify-center rounded-[11px] bg-[#FFF0F0] text-[#C76161]"><Trash2 className="h-[16px] w-[16px]" /></div>
            <AlertDialogTitle className="text-[14px] font-semibold text-[#343A44]">حذف القسم</AlertDialogTitle>
            <AlertDialogDescription className="text-[9px] leading-6 text-[#858D97]">سيتم حذف قسم "{deleteTarget?.name || ""}" وروابط المنتجات الموجودة داخله. المنتجات نفسها لن تُحذف.</AlertDialogDescription>
          </AlertDialogHeader>

          <AlertDialogFooter className="mt-2 gap-2">
            <AlertDialogCancel className="h-[38px] rounded-[9px] border-[#E2E6EB] bg-white px-4 text-[9px] font-semibold text-[#6B737E]">إلغاء</AlertDialogCancel>
            <AlertDialogAction disabled={del.isPending} onClick={(event) => { event.preventDefault(); if (deleteTarget) del.mutate(deleteTarget); }} className="h-[38px] rounded-[9px] bg-[#C76161] px-4 text-[9px] font-semibold text-white hover:bg-[#B65555]">{del.isPending && <Loader2 className="ml-[5px] h-[11px] w-[11px] animate-spin" />}حذف نهائي</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

const SectionStatCard = ({ title, value, helper, icon: Icon, tone }: { title: string; value: number; helper: string; icon: LucideIcon; tone: "indigo" | "green" | "blue" | "coral" }) => {
  const style = {
    indigo: { icon: "bg-[#F1EFFF] text-[#675CBA]", line: "bg-[#675CBA]" },
    green: { icon: "bg-[#EAF7EE] text-[#629067]", line: "bg-[#629067]" },
    blue: { icon: "bg-[#EDF4FF] text-[#5680CF]", line: "bg-[#5680CF]" },
    coral: { icon: "bg-[#FFF0ED] text-[#D06A5E]", line: "bg-[#D06A5E]" },
  }[tone];

  return <article className="relative min-h-[116px] overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white p-[13px]"><span className={cn("absolute inset-x-0 top-0 h-[3px]", style.line)} /><div className={cn("flex h-[32px] w-[32px] items-center justify-center rounded-[10px]", style.icon)}><Icon className="h-[14px] w-[14px]" /></div><p className="mt-[12px] text-[8.5px] text-[#8D949E]">{title}</p><p className="mt-[4px] text-[20px] font-semibold leading-none text-[#303741]">{value.toLocaleString("en-US")}</p><p className="mt-[6px] text-[7px] text-[#A0A6AF]">{helper}</p></article>;
};

const SectionImage = ({ section, mobile = false }: { section: Section; mobile?: boolean }) => {
  const box = mobile ? "h-[62px] w-[62px] rounded-[11px]" : "h-[48px] w-[48px] rounded-[9px]";

  return <div className={cn("flex shrink-0 items-center justify-center overflow-hidden border border-[#E8EBEF] bg-[#F5F6F8]", box)}>{section.image_url ? <img src={section.image_url} alt={section.name} loading="lazy" className="h-full w-full object-cover" /> : <Package className="h-[14px] w-[14px] text-[#9AA1AB]" />}</div>;
};

const SectionStatus = ({ active }: { active: boolean }) => {
  return <span className={cn("inline-flex h-[24px] items-center gap-[5px] rounded-[7px] border px-[7px] text-[6.5px] font-semibold", active ? "border-[#D8E8DD] bg-[#EFF8F2] text-[#568468]" : "border-[#E3E6EA] bg-[#F5F6F8] text-[#818994]")}><span className={cn("h-[5px] w-[5px] rounded-full", active ? "bg-[#629067]" : "bg-[#969EA8]")} />{active ? "نشط" : "معطل"}</span>;
};

const FormSection = ({ title, icon: Icon, children }: { title: string; icon: LucideIcon; children: ReactNode }) => {
  return <section className="rounded-[14px] border border-[#E5E9EF] bg-white p-[12px]"><div className="mb-[10px] flex items-center gap-[7px] border-b border-[#F0F2F5] pb-[8px]"><div className="flex h-[28px] w-[28px] items-center justify-center rounded-[8px] bg-[#F1EFFF] text-[#675CBA]"><Icon className="h-[11px] w-[11px]" /></div><h3 className="text-[9.5px] font-semibold text-[#4A525C]">{title}</h3></div><div className="space-y-[9px]">{children}</div></section>;
};

const Field = ({ label, children, required = false }: { label: string; children: ReactNode; required?: boolean }) => {
  return <div><Label className="mb-[6px] block text-[8px] font-semibold text-[#727A84]">{label}{required && <span className="mr-[3px] text-[#C76161]">*</span>}</Label>{children}</div>;
};

const EmptySections = () => {
  return <div className="flex min-h-[230px] flex-col items-center justify-center rounded-[14px] bg-white px-6 text-center"><div className="flex h-[45px] w-[45px] items-center justify-center rounded-[13px] bg-[#F0F2F5] text-[#8C949E]"><Package className="h-[18px] w-[18px]" /></div><h3 className="mt-3 text-[10px] font-semibold text-[#535B65]">لا توجد أقسام</h3><p className="mt-[4px] text-[7px] text-[#9BA2AC]">أضف أول قسم لهذه الماركة للبدء.</p></div>;
};

export default AdminBrandSectionsPage;