import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { toast } from "@/hooks/use-toast";
import { ArrowRight, CheckCircle2, ChevronDown, ChevronUp, CircleOff, Filter as FilterIcon, Layers3, ListFilter, Loader2, Package, Pencil, Plus, Search, SlidersHorizontal, Trash2, X, type LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";

interface FilterRow {
  id: string;
  brand_id: string | null;
  section_id: string;
  name: string;
  slug: string;
  filter_type: string;
  options: string[];
  sort_order: number | null;
  is_active: boolean | null;
}

interface BrandRow {
  id: string;
  name: string;
}

interface SectionRow {
  id: string;
  name: string;
  is_active: boolean | null;
}

interface ProductFilterLink {
  filter_id: string;
}

type FilterForm = {
  name: string;
  slug: string;
  filter_type: string;
  optionsText: string;
  sort_order: number;
  is_active: boolean;
};

const filterTypes = [
  { value: "multi", label: "اختيارات متعددة", helper: "يمكن للعميل اختيار أكثر من قيمة" },
  { value: "single", label: "اختيار واحد", helper: "قيمة واحدة فقط من الخيارات" },
  { value: "range", label: "نطاق", helper: "مناسب للسعر أو القيم الرقمية" },
];

const slugify = (value: string) => value.toLowerCase().trim().replace(/[^\w\u0600-\u06FF]+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "");

const emptyForm = (sortOrder = 0): FilterForm => ({
  name: "",
  slug: "",
  filter_type: "multi",
  optionsText: "",
  sort_order: sortOrder,
  is_active: true,
});

const AdminBrandFiltersPage = () => {
  const { id: routeBrandId } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [selectedBrandId, setSelectedBrandId] = useState<string | undefined>(routeBrandId);
  const [selectedSectionId, setSelectedSectionId] = useState<string | undefined>(() => {
    if (!routeBrandId) return undefined;
    return sessionStorage.getItem(`admin-brand-filter-section:${routeBrandId}`) || undefined;
  });

  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<FilterRow | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<FilterRow | null>(null);
  const [form, setForm] = useState<FilterForm>(emptyForm());
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [search, setSearch] = useState("");
  const [movingId, setMovingId] = useState<string | null>(null);

  /* =========================================================
     BRANDS
  ========================================================= */

  const { data: brands = [], isLoading: brandsLoading } = useQuery({
    queryKey: ["all-brands-filters"],
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brands").select("id,name").order("sort_order", { ascending: true }).order("name", { ascending: true });

      if (error) throw error;

      return (data || []) as BrandRow[];
    },
    staleTime: 60_000,
  });

  const activeBrandId = selectedBrandId || brands[0]?.id || "";
  const activeBrand = useMemo(() => brands.find((brand) => brand.id === activeBrandId) || null, [brands, activeBrandId]);

  /* =========================================================
     SECTIONS
  ========================================================= */

  const { data: sections = [], isLoading: sectionsLoading } = useQuery({
    queryKey: ["brand-sections-filters", activeBrandId],
    enabled: Boolean(activeBrandId),
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brand_sections").select("id,name,is_active").eq("brand_id", activeBrandId).order("sort_order", { ascending: true }).order("name", { ascending: true });

      if (error) throw error;

      return (data || []) as SectionRow[];
    },
    staleTime: 30_000,
  });

  useEffect(() => {
    if (!activeBrandId || sectionsLoading) return;

    const currentIsValid = Boolean(selectedSectionId && sections.some((section) => section.id === selectedSectionId));

    if (currentIsValid) return;

    const stored = sessionStorage.getItem(`admin-brand-filter-section:${activeBrandId}`);
    const storedIsValid = Boolean(stored && sections.some((section) => section.id === stored));

    const nextSectionId = storedIsValid ? stored! : sections.find((section) => section.is_active)?.id || sections[0]?.id;

    setSelectedSectionId(nextSectionId);

    if (nextSectionId) {
      sessionStorage.setItem(`admin-brand-filter-section:${activeBrandId}`, nextSectionId);
    } else {
      sessionStorage.removeItem(`admin-brand-filter-section:${activeBrandId}`);
    }
  }, [activeBrandId, sections, sectionsLoading, selectedSectionId]);

  const activeSection = useMemo(() => sections.find((section) => section.id === selectedSectionId) || null, [sections, selectedSectionId]);

  const selectBrand = (brandId: string) => {
    setSelectedBrandId(brandId);

    const stored = sessionStorage.getItem(`admin-brand-filter-section:${brandId}`) || undefined;
    setSelectedSectionId(stored);

    setSearch("");
  };

  const selectSection = (sectionId: string) => {
    setSelectedSectionId(sectionId);

    if (activeBrandId) {
      sessionStorage.setItem(`admin-brand-filter-section:${activeBrandId}`, sectionId);
    }

    setSearch("");
  };

  /* =========================================================
     FILTERS
  ========================================================= */

  const { data: filters = [], isLoading, isFetching } = useQuery({
    queryKey: ["brand-filters-admin", activeBrandId, selectedSectionId],
    enabled: Boolean(activeBrandId && selectedSectionId),
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brand_filters").select("id,brand_id,section_id,name,slug,filter_type,options,sort_order,is_active").eq("brand_id", activeBrandId).eq("section_id", selectedSectionId).order("sort_order", { ascending: true }).order("name", { ascending: true });

      if (error) throw error;

      return (data || []).map((filter: any) => ({
        ...filter,
        options: Array.isArray(filter.options) ? filter.options.map(String) : [],
      })) as FilterRow[];
    },
    staleTime: 20_000,
  });

  const filterIds = useMemo(() => filters.map((filter) => filter.id), [filters]);

  const { data: productFilterLinks = [] } = useQuery({
    queryKey: ["brand-filter-product-links", filterIds],
    enabled: filterIds.length > 0,
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("product_brand_filters").select("filter_id").in("filter_id", filterIds);

      if (error) throw error;

      return (data || []) as ProductFilterLink[];
    },
    staleTime: 20_000,
  });

  const productCounts = useMemo(() => {
    return productFilterLinks.reduce<Record<string, number>>((accumulator, row) => {
      accumulator[row.filter_id] = (accumulator[row.filter_id] || 0) + 1;
      return accumulator;
    }, {});
  }, [productFilterLinks]);

  const stats = useMemo(() => {
    const active = filters.filter((filter) => filter.is_active).length;
    const optionsCount = filters.reduce((sum, filter) => sum + filter.options.length, 0);
    const used = filters.filter((filter) => (productCounts[filter.id] || 0) > 0).length;

    return {
      total: filters.length,
      active,
      inactive: filters.length - active,
      optionsCount,
      used,
    };
  }, [filters, productCounts]);

  const filteredFilters = useMemo(() => {
    const query = search.trim().toLowerCase();

    if (!query) return filters;

    return filters.filter((filter) => {
      const optionsText = filter.options.join(" ").toLowerCase();
      return filter.name.toLowerCase().includes(query) || filter.slug.toLowerCase().includes(query) || optionsText.includes(query);
    });
  }, [filters, search]);

  /* =========================================================
     FORM
  ========================================================= */

  const resetForm = () => {
    setForm(emptyForm(filters.length));
    setEditing(null);
    setSlugAutoGenerated(true);
    setDialogOpen(false);
  };

  const openNew = () => {
    if (!activeBrandId) {
      toast({ title: "اختر الماركة أولًا", variant: "destructive" });
      return;
    }

    if (!selectedSectionId) {
      toast({ title: "اختر القسم أولًا", description: "يجب أن يكون الفلتر تابعًا لقسم محدد.", variant: "destructive" });
      return;
    }

    setEditing(null);
    setSlugAutoGenerated(true);
    setForm(emptyForm(filters.length));
    setDialogOpen(true);
  };

  const openEdit = (filter: FilterRow) => {
    setEditing(filter);
    setSlugAutoGenerated(false);
    setForm({
      name: filter.name,
      slug: filter.slug,
      filter_type: filter.filter_type || "multi",
      optionsText: (filter.options || []).join("\n"),
      sort_order: filter.sort_order ?? 0,
      is_active: filter.is_active ?? true,
    });
    setDialogOpen(true);
  };

  const handleNameChange = (name: string) => {
    setForm((current) => ({
      ...current,
      name,
      slug: slugAutoGenerated ? slugify(name) : current.slug,
    }));
  };

  const handleSlugChange = (slug: string) => {
    setSlugAutoGenerated(false);
    setForm((current) => ({ ...current, slug: slugify(slug) }));
  };

  /* =========================================================
     SAVE
  ========================================================= */

  const save = useMutation({
    mutationFn: async () => {
      if (!activeBrandId) throw new Error("اختر ماركة أولًا.");
      if (!selectedSectionId) throw new Error("اختر القسم أولًا.");

      const name = form.name.trim();
      const slug = slugify(form.slug || name);

      if (!name) throw new Error("اسم الفلتر مطلوب.");
      if (!slug) throw new Error("تعذر إنشاء رابط صالح للفلتر.");

      const options = Array.from(new Set(form.optionsText.split("\n").map((value) => value.trim()).filter(Boolean)));

      let duplicateQuery = (supabase as any).from("brand_filters").select("id").eq("section_id", selectedSectionId).eq("slug", slug).limit(1);

      if (editing) duplicateQuery = duplicateQuery.neq("id", editing.id);

      const { data: duplicated, error: duplicateError } = await duplicateQuery;

      if (duplicateError) throw duplicateError;

      if ((duplicated || []).length > 0) {
        throw new Error(`الرابط "${slug}" مستخدم في فلتر آخر داخل هذا القسم.`);
      }

      const payload = {
        brand_id: activeBrandId,
        section_id: selectedSectionId,
        name,
        slug,
        filter_type: form.filter_type,
        options,
        sort_order: Math.max(0, Number(form.sort_order || 0)),
        is_active: form.is_active,
      };

      if (editing) {
        const { error } = await (supabase as any).from("brand_filters").update(payload).eq("id", editing.id);
        if (error) throw error;
        return;
      }

      const { error } = await (supabase as any).from("brand_filters").insert(payload);
      if (error) throw error;
    },

    onSuccess: async () => {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["brand-filters-admin", activeBrandId, selectedSectionId] }),
        queryClient.invalidateQueries({ queryKey: ["brand-filter-product-links"] }),
        queryClient.invalidateQueries({ queryKey: ["brand-page-filters"] }),
      ]);

      toast({
        title: editing ? "تم تحديث الفلتر" : "تمت إضافة الفلتر",
        description: activeSection?.name ? `تم حفظ الفلتر داخل قسم ${activeSection.name}.` : undefined,
      });

      resetForm();
    },

    onError: (error: any) => {
      toast({
        title: "تعذر حفظ الفلتر",
        description: error?.message || "حدث خطأ أثناء الحفظ.",
        variant: "destructive",
      });
    },
  });

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    save.mutate();
  };

  /* =========================================================
     ACTIVE
  ========================================================= */

  const toggleActiveMutation = useMutation({
    mutationFn: async ({ id, is_active }: { id: string; is_active: boolean }) => {
      const { error } = await (supabase as any).from("brand_filters").update({ is_active }).eq("id", id);

      if (error) throw error;

      return { id, is_active };
    },

    onMutate: async ({ id, is_active }) => {
      const queryKey = ["brand-filters-admin", activeBrandId, selectedSectionId] as const;

      await queryClient.cancelQueries({ queryKey });

      const previous = queryClient.getQueryData<FilterRow[]>(queryKey);

      queryClient.setQueryData<FilterRow[]>(queryKey, (current = []) => current.map((filter) => filter.id === id ? { ...filter, is_active } : filter));

      return { previous, queryKey };
    },

    onError: (error: any, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(context.queryKey, context.previous);

      toast({
        title: "تعذر تحديث الحالة",
        description: error?.message || "حدث خطأ.",
        variant: "destructive",
      });
    },

    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ["brand-filters-admin", activeBrandId, selectedSectionId] });
    },
  });

  /* =========================================================
     ORDER
  ========================================================= */

  const moveFilter = async (filter: FilterRow, direction: "up" | "down") => {
    const index = filters.findIndex((item) => item.id === filter.id);
    if (index < 0) return;

    const newIndex = direction === "up" ? index - 1 : index + 1;
    if (newIndex < 0 || newIndex >= filters.length) return;

    const queryKey = ["brand-filters-admin", activeBrandId, selectedSectionId] as const;
    const previous = [...filters];
    const reordered = [...filters];

    const current = reordered[index];
    reordered[index] = reordered[newIndex];
    reordered[newIndex] = current;

    const normalized = reordered.map((item, itemIndex) => ({ ...item, sort_order: itemIndex }));

    setMovingId(filter.id);
    queryClient.setQueryData(queryKey, normalized);

    try {
      const results = await Promise.all(normalized.map((item) => (supabase as any).from("brand_filters").update({ sort_order: item.sort_order }).eq("id", item.id)));
      const failed = results.find((result) => result.error);

      if (failed?.error) throw failed.error;

      toast({ title: "تم تحديث ترتيب الفلاتر" });
    } catch (error: any) {
      queryClient.setQueryData(queryKey, previous);

      toast({
        title: "تعذر تحديث الترتيب",
        description: error?.message || "حدث خطأ.",
        variant: "destructive",
      });
    } finally {
      setMovingId(null);
    }
  };

  /* =========================================================
     DELETE
  ========================================================= */

  const del = useMutation({
    mutationFn: async (filter: FilterRow) => {
      const { error } = await (supabase as any).from("brand_filters").delete().eq("id", filter.id);

      if (error) throw error;
    },

    onSuccess: async () => {
      setDeleteTarget(null);

      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["brand-filters-admin", activeBrandId, selectedSectionId] }),
        queryClient.invalidateQueries({ queryKey: ["brand-filter-product-links"] }),
        queryClient.invalidateQueries({ queryKey: ["brand-page-filters"] }),
      ]);

      toast({ title: "تم حذف الفلتر" });
    },

    onError: (error: any) => {
      toast({
        title: "تعذر حذف الفلتر",
        description: error?.message || "حدث خطأ أثناء الحذف.",
        variant: "destructive",
      });
    },
  });

  /* =========================================================
     RENDER
  ========================================================= */

  return (
    <div className="w-full space-y-4" dir="rtl">
      <AdminPageHeader category="الماركات" title="فلاتر الماركة" description={activeSection ? `إدارة فلاتر قسم ${activeSection.name}` : "أنشئ فلاتر مخصصة لكل قسم داخل صفحة الماركة"} actions={[{ label: "رجوع", icon: ArrowRight, onClick: () => navigate("/admin/brand-pages"), variant: "secondary" }, { label: "إضافة فلتر", icon: Plus, onClick: openNew, variant: "primary" }]} />

      <section className="grid grid-cols-2 gap-[9px] lg:grid-cols-4">
        <FilterStatCard title="إجمالي الفلاتر" value={stats.total} helper={activeSection?.name || "القسم الحالي"} icon={ListFilter} tone="indigo" />
        <FilterStatCard title="الفلاتر النشطة" value={stats.active} helper={`${stats.inactive} فلتر معطل`} icon={CheckCircle2} tone="green" />
        <FilterStatCard title="إجمالي الخيارات" value={stats.optionsCount} helper="كل القيم المتاحة للعملاء" icon={SlidersHorizontal} tone="blue" />
        <FilterStatCard title="مستخدمة بمنتجات" value={stats.used} helper="لديها روابط منتجات فعلية" icon={Package} tone="coral" />
      </section>

      <section className="overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white">
        <div className="flex items-center justify-between border-b border-[#EDF0F3] px-[13px] py-[10px]">
          <div>
            <h2 className="text-[11px] font-semibold text-[#444B55]">الماركة والقسم</h2>
            <p className="mt-[3px] text-[8px] text-[#9BA2AC]">كل فلتر مرتبط بقسم محدد داخل صفحة الماركة</p>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-[7px] p-[11px] lg:grid-cols-2">
          <Select value={activeBrandId} onValueChange={selectBrand} disabled={brandsLoading}>
            <SelectTrigger className="h-[40px] rounded-[9px] border-[#E3E7EC] bg-[#F8FAFC] text-[9px] shadow-none focus:ring-0">
              <SelectValue placeholder="اختر ماركة" />
            </SelectTrigger>

            <SelectContent>
              {brands.map((brand) => <SelectItem key={brand.id} value={brand.id}>{brand.name}</SelectItem>)}
            </SelectContent>
          </Select>

          <Select value={selectedSectionId || ""} onValueChange={selectSection} disabled={sectionsLoading || sections.length === 0}>
            <SelectTrigger className="h-[40px] rounded-[9px] border-[#E3E7EC] bg-[#F8FAFC] text-[9px] shadow-none focus:ring-0">
              <SelectValue placeholder={sections.length === 0 ? "لا توجد أقسام لهذه الماركة" : "اختر القسم"} />
            </SelectTrigger>

            <SelectContent>
              {sections.map((section) => <SelectItem key={section.id} value={section.id}>{section.name}{!section.is_active ? " — معطل" : ""}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </section>

      {!sectionsLoading && activeBrandId && sections.length === 0 && (
        <section className="rounded-[12px] border border-[#EEDFC4] bg-[#FFF9EF] px-[11px] py-[9px]">
          <p className="text-[8px] font-semibold text-[#9A7139]">لا توجد أقسام لهذه الماركة</p>
          <p className="mt-[3px] text-[7px] leading-5 text-[#8A7659]">أنشئ قسمًا في صفحة أقسام الماركة أولًا، وبعدها يمكنك إضافة الفلاتر له.</p>
        </section>
      )}

      <section className="overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white">
        <div className="flex items-center justify-between border-b border-[#EDF0F3] px-[13px] py-[10px]">
          <div>
            <h2 className="text-[11px] font-semibold text-[#444B55]">البحث</h2>
            <p className="mt-[3px] text-[8px] text-[#9BA2AC]">ابحث باسم الفلتر أو الرابط أو أحد الخيارات</p>
          </div>

          {search && (
            <button type="button" onClick={() => setSearch("")} className="flex h-[30px] items-center gap-[5px] rounded-[8px] px-[8px] text-[8px] font-semibold text-[#7E8690] hover:bg-[#F7F8FA]">
              <X className="h-[10px] w-[10px]" />
              مسح البحث
            </button>
          )}
        </div>

        <div className="p-[11px]">
          <div className="relative">
            <Search className="pointer-events-none absolute right-[12px] top-1/2 h-[13px] w-[13px] -translate-y-1/2 text-[#969EA8]" />
            <Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="اسم الفلتر، slug أو خيار..." className="h-[40px] rounded-[9px] border-[#E3E7EC] bg-[#F8FAFC] pr-[35px] text-[10px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
          </div>
        </div>
      </section>

      <section className="hidden overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white md:block">
        <div className="flex items-center justify-between border-b border-[#EAEDF1] px-[13px] py-[10px]">
          <div>
            <h2 className="text-[11px] font-semibold text-[#454C56]">فلاتر {activeSection?.name || "القسم"}</h2>
            <p className="mt-[3px] text-[8px] text-[#9CA3AC]">{filteredFilters.length.toLocaleString("ar-EG")} فلتر ظاهر</p>
          </div>

          {isFetching && <Loader2 className="h-[12px] w-[12px] animate-spin text-[#8E959F]" />}
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1050px]">
            <thead>
              <tr className="h-[42px] border-b border-[#EAEDF1] bg-[#FAFBFC] text-[9px] font-semibold text-[#858D97]">
                <th className="w-[68px] px-[10px] text-center">الترتيب</th>
                <th className="px-[12px] text-right">الفلتر</th>
                <th className="px-[12px] text-right">النوع</th>
                <th className="px-[12px] text-right">الخيارات</th>
                <th className="px-[12px] text-right">المنتجات</th>
                <th className="px-[12px] text-right">الحالة</th>
                <th className="w-[110px] px-[12px] text-center">الإجراءات</th>
              </tr>
            </thead>

            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan={7} className="h-[260px] text-center"><Loader2 className="mx-auto h-[20px] w-[20px] animate-spin text-[#675CBA]" /></td>
                </tr>
              ) : !selectedSectionId ? (
                <tr>
                  <td colSpan={7}><EmptyFilters text="اختر قسمًا لعرض فلاتره." /></td>
                </tr>
              ) : filteredFilters.length === 0 ? (
                <tr>
                  <td colSpan={7}><EmptyFilters text="لا توجد فلاتر مطابقة داخل هذا القسم." /></td>
                </tr>
              ) : (
                filteredFilters.map((filter) => {
                  const index = filters.findIndex((item) => item.id === filter.id);
                  const type = filterTypes.find((item) => item.value === filter.filter_type);
                  const productsCount = productCounts[filter.id] || 0;

                  return (
                    <tr key={filter.id} className="h-[70px] border-b border-[#F0F2F5] transition-colors last:border-b-0 hover:bg-[#FCFDFE]">
                      <td className="px-[10px]">
                        <div className="flex items-center justify-center gap-[2px]">
                          <div className="flex flex-col">
                            <button type="button" disabled={index <= 0 || Boolean(movingId)} onClick={() => void moveFilter(filter, "up")} className="flex h-[20px] w-[24px] items-center justify-center rounded-[6px] text-[#8D949E] hover:bg-[#F1F3F6] disabled:opacity-25"><ChevronUp className="h-[9px] w-[9px]" /></button>
                            <button type="button" disabled={index >= filters.length - 1 || Boolean(movingId)} onClick={() => void moveFilter(filter, "down")} className="flex h-[20px] w-[24px] items-center justify-center rounded-[6px] text-[#8D949E] hover:bg-[#F1F3F6] disabled:opacity-25"><ChevronDown className="h-[9px] w-[9px]" /></button>
                          </div>

                          <span className="text-[7px] font-semibold text-[#9BA2AC]">{movingId === filter.id ? <Loader2 className="h-[9px] w-[9px] animate-spin" /> : index + 1}</span>
                        </div>
                      </td>

                      <td className="px-[12px]">
                        <div className="min-w-[190px]">
                          <p className="max-w-[230px] truncate text-[10.5px] font-semibold text-[#414953]">{filter.name}</p>
                          <p dir="ltr" className="mt-[3px] max-w-[220px] truncate text-right text-[7px] text-[#9AA2AC]">/{filter.slug}</p>
                        </div>
                      </td>

                      <td className="px-[12px]">
                        <span className="inline-flex h-[25px] items-center gap-[5px] rounded-[7px] border border-[#E2DEF3] bg-[#F6F4FF] px-[7px] text-[6.5px] font-semibold text-[#675CBA]"><SlidersHorizontal className="h-[8px] w-[8px]" />{type?.label || filter.filter_type}</span>
                      </td>

                      <td className="px-[12px]">
                        <div className="flex max-w-[320px] flex-wrap gap-[4px]">
                          {filter.options.slice(0, 4).map((option) => <span key={option} className="rounded-[6px] bg-[#F2F4F7] px-[6px] py-[3px] text-[6.5px] font-medium text-[#707883]">{option}</span>)}
                          {filter.options.length > 4 && <span className="rounded-[6px] bg-[#EDF4FF] px-[6px] py-[3px] text-[6.5px] font-semibold text-[#5680CF]">+{filter.options.length - 4}</span>}
                          {filter.options.length === 0 && <span className="text-[7px] text-[#A0A6AF]">بدون خيارات</span>}
                        </div>
                      </td>

                      <td className="px-[12px]">
                        <span className={cn("inline-flex h-[25px] items-center gap-[5px] rounded-[7px] border px-[7px] text-[6.5px] font-semibold", productsCount > 0 ? "border-[#DCE7F4] bg-[#F1F6FC] text-[#5679A4]" : "border-[#E4E7EB] bg-[#F5F6F8] text-[#858D97]")}><Package className="h-[8px] w-[8px]" />{productsCount} منتج</span>
                      </td>

                      <td className="px-[12px]">
                        <div className="flex items-center gap-[8px]">
                          <Switch checked={filter.is_active ?? true} onCheckedChange={(checked) => toggleActiveMutation.mutate({ id: filter.id, is_active: checked })} />
                          <FilterStatus active={Boolean(filter.is_active)} />
                        </div>
                      </td>

                      <td className="px-[12px]">
                        <div className="flex items-center justify-center gap-[4px]">
                          <button type="button" onClick={() => openEdit(filter)} className="flex h-[30px] w-[30px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[#675CBA] hover:bg-[#F5F3FF]"><Pencil className="h-[11px] w-[11px]" /></button>
                          <button type="button" onClick={() => setDeleteTarget(filter)} className="flex h-[30px] w-[30px] items-center justify-center rounded-[8px] border border-[#F0D7D4] bg-white text-[#C15F56] hover:bg-[#FFF3F1]"><Trash2 className="h-[11px] w-[11px]" /></button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-[8px] md:hidden">
        {!selectedSectionId ? (
          <EmptyFilters text="اختر قسمًا لعرض فلاتره." />
        ) : isLoading ? (
          <div className="flex h-[220px] items-center justify-center rounded-[14px] border border-[#E5E9EF] bg-white"><Loader2 className="h-[20px] w-[20px] animate-spin text-[#675CBA]" /></div>
        ) : filteredFilters.length === 0 ? (
          <EmptyFilters text="لا توجد فلاتر مطابقة داخل هذا القسم." />
        ) : (
          filteredFilters.map((filter) => {
            const index = filters.findIndex((item) => item.id === filter.id);
            const productsCount = productCounts[filter.id] || 0;

            return (
              <article key={filter.id} className="overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white">
                <div className="p-[11px]">
                  <div className="flex items-start justify-between gap-[7px]">
                    <div className="min-w-0">
                      <h3 className="truncate text-[11px] font-semibold text-[#3B424C]">{filter.name}</h3>
                      <p dir="ltr" className="mt-[3px] truncate text-right text-[7px] text-[#9299A3]">/{filter.slug}</p>
                    </div>

                    <FilterStatus active={Boolean(filter.is_active)} />
                  </div>

                  <div className="mt-[8px] flex flex-wrap gap-[5px]">
                    <span className="rounded-[6px] bg-[#F6F4FF] px-[7px] py-[4px] text-[7px] font-semibold text-[#675CBA]">{filterTypes.find((item) => item.value === filter.filter_type)?.label || filter.filter_type}</span>
                    <span className="rounded-[6px] bg-[#EDF4FF] px-[7px] py-[4px] text-[7px] font-semibold text-[#5680CF]">{productsCount} منتج</span>
                    <span className="rounded-[6px] bg-[#F2F4F7] px-[7px] py-[4px] text-[7px] font-semibold text-[#757D87]">{filter.options.length} خيارات</span>
                  </div>

                  {filter.options.length > 0 && <p className="mt-[7px] line-clamp-2 text-[7px] leading-5 text-[#858D97]">{filter.options.slice(0, 6).join(" • ")}</p>}
                </div>

                <div className="grid grid-cols-[38px_38px_1fr_42px] gap-[5px] border-t border-[#EDF0F3] bg-[#FAFBFC] p-[7px]">
                  <button type="button" disabled={index <= 0 || Boolean(movingId)} onClick={() => void moveFilter(filter, "up")} className="flex h-[35px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[#7C848E] disabled:opacity-30"><ChevronUp className="h-[10px] w-[10px]" /></button>
                  <button type="button" disabled={index >= filters.length - 1 || Boolean(movingId)} onClick={() => void moveFilter(filter, "down")} className="flex h-[35px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[#7C848E] disabled:opacity-30"><ChevronDown className="h-[10px] w-[10px]" /></button>
                  <button type="button" onClick={() => openEdit(filter)} className="flex h-[35px] items-center justify-center gap-[5px] rounded-[8px] border border-[#E2DEF3] bg-white text-[8px] font-semibold text-[#675CBA]"><Pencil className="h-[10px] w-[10px]" />تعديل</button>
                  <button type="button" onClick={() => setDeleteTarget(filter)} className="flex h-[35px] w-[42px] items-center justify-center rounded-[8px] border border-[#F0D7D4] bg-white text-[#C15F56]"><Trash2 className="h-[11px] w-[11px]" /></button>
                </div>
              </article>
            );
          })
        )}
      </section>

      <Dialog open={dialogOpen} onOpenChange={(open) => { if (!open && !save.isPending) resetForm(); else if (open) setDialogOpen(true); }}>
        <DialogContent dir="rtl" className="max-h-[92vh] max-w-[680px] overflow-y-auto rounded-[18px] border-[#E4E8ED] bg-[#F7F8FA] p-0">
          <DialogHeader className="sticky top-0 z-20 border-b border-[#E6E9EE] bg-white px-5 py-4">
            <div className="flex items-center gap-[10px]">
              <div className="flex h-[36px] w-[36px] items-center justify-center rounded-[11px] bg-[#F1EFFF] text-[#675CBA]">{editing ? <Pencil className="h-[15px] w-[15px]" /> : <Plus className="h-[15px] w-[15px]" />}</div>
              <div>
                <DialogTitle className="text-right text-[14px] font-semibold text-[#343B45]">{editing ? "تعديل الفلتر" : "إضافة فلتر جديد"}</DialogTitle>
                <DialogDescription className="mt-[3px] text-right text-[8px] text-[#9299A3]">{activeBrand?.name || "الماركة"} / {activeSection?.name || "القسم"}</DialogDescription>
              </div>
            </div>
          </DialogHeader>

          <form onSubmit={handleSubmit}>
            <div className="space-y-[10px] p-[10px]">
              <FormSection title="بيانات الفلتر" icon={FilterIcon}>
                <Field label="اسم الفلتر" required>
                  <Input value={form.name} onChange={(event) => handleNameChange(event.target.value)} placeholder="مثال: اللون، المقاس، الخامة" className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9.5px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                </Field>

                <Field label="الرابط">
                  <Input value={form.slug} placeholder={slugify(form.name) || "filter-slug"} onChange={(event) => handleSlugChange(event.target.value)} dir="ltr" className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                </Field>

                <Field label="نوع الفلتر">
                  <Select value={form.filter_type} onValueChange={(value) => setForm((current) => ({ ...current, filter_type: value }))}>
                    <SelectTrigger className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus:ring-0"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {filterTypes.map((type) => <SelectItem key={type.value} value={type.value}>{type.label}</SelectItem>)}
                    </SelectContent>
                  </Select>

                  <p className="mt-[5px] text-[6.5px] leading-5 text-[#9BA2AC]">{filterTypes.find((type) => type.value === form.filter_type)?.helper}</p>
                </Field>
              </FormSection>

              <FormSection title="خيارات الفلتر" icon={SlidersHorizontal}>
                <Field label="كل خيار في سطر مستقل">
                  <Textarea rows={7} value={form.optionsText} onChange={(event) => setForm((current) => ({ ...current, optionsText: event.target.value }))} placeholder={"صغير\nمتوسط\nكبير"} className="resize-none rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] leading-6 shadow-none focus-visible:bg-white focus-visible:ring-0" />
                </Field>

                <div className="rounded-[10px] border border-[#E7EAEF] bg-[#FAFBFC] p-[9px]">
                  <p className="text-[7px] font-semibold text-[#6F7781]">المعاينة</p>

                  <div className="mt-[6px] flex flex-wrap gap-[4px]">
                    {Array.from(new Set(form.optionsText.split("\n").map((value) => value.trim()).filter(Boolean))).slice(0, 12).map((option) => <span key={option} className="rounded-[6px] bg-white px-[6px] py-[3px] text-[6.5px] font-medium text-[#707883] ring-1 ring-[#E5E9EF]">{option}</span>)}
                    {!form.optionsText.trim() && <span className="text-[6.5px] text-[#A0A6AF]">ستظهر الخيارات هنا.</span>}
                  </div>
                </div>
              </FormSection>

              <FormSection title="العرض والترتيب" icon={Layers3}>
                <div className="grid grid-cols-1 gap-[8px] sm:grid-cols-2">
                  <Field label="ترتيب العرض">
                    <Input type="number" min={0} value={form.sort_order} onChange={(event) => setForm((current) => ({ ...current, sort_order: Number.parseInt(event.target.value, 10) || 0 }))} className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                  </Field>

                  <div className="flex min-h-[64px] items-center justify-between rounded-[10px] border border-[#E6E9EE] bg-[#FAFBFC] px-[10px]">
                    <div>
                      <p className="text-[8.5px] font-semibold text-[#555D67]">حالة الفلتر</p>
                      <p className="mt-[2px] text-[6.5px] text-[#9BA2AC]">{form.is_active ? "ظاهر للعملاء" : "مخفي"}</p>
                    </div>
                    <Switch checked={form.is_active} onCheckedChange={(value) => setForm((current) => ({ ...current, is_active: value }))} />
                  </div>
                </div>
              </FormSection>
            </div>

            <div className="sticky bottom-0 z-20 flex items-center justify-end gap-[7px] border-t border-[#E5E9EF] bg-white px-5 py-3">
              <Button type="button" variant="outline" disabled={save.isPending} onClick={resetForm} className="h-[36px] rounded-[9px] border-[#E1E5EA] bg-white px-4 text-[8px] font-semibold text-[#707883] shadow-none">إلغاء</Button>
              <Button type="submit" disabled={save.isPending || !selectedSectionId} className="h-[36px] rounded-[9px] bg-[#675CBA] px-5 text-[8px] font-semibold text-white shadow-none hover:bg-[#594FAB]">{save.isPending ? <Loader2 className="ml-[5px] h-[11px] w-[11px] animate-spin" /> : editing ? <Pencil className="ml-[5px] h-[11px] w-[11px]" /> : <Plus className="ml-[5px] h-[11px] w-[11px]" />}{editing ? "حفظ التعديلات" : "إضافة الفلتر"}</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null); }}>
        <AlertDialogContent dir="rtl" className="max-w-[420px] rounded-[15px] border-[#E4E8ED] bg-white p-5">
          <AlertDialogHeader>
            <div className="mb-2 flex h-[38px] w-[38px] items-center justify-center rounded-[11px] bg-[#FFF0F0] text-[#C76161]"><Trash2 className="h-[16px] w-[16px]" /></div>
            <AlertDialogTitle className="text-[14px] font-semibold text-[#343A44]">حذف الفلتر</AlertDialogTitle>
            <AlertDialogDescription className="text-[9px] leading-6 text-[#858D97]">سيتم حذف فلتر "{deleteTarget?.name || ""}". روابطه بالمنتجات ستُحذف تلقائيًا، لكن المنتجات نفسها لن تُحذف.</AlertDialogDescription>
          </AlertDialogHeader>

          <AlertDialogFooter className="mt-2 gap-2">
            <AlertDialogCancel className="h-[38px] rounded-[9px] border-[#E2E6EB] bg-white px-4 text-[9px] font-semibold text-[#6B737E]">إلغاء</AlertDialogCancel>
            <AlertDialogAction disabled={del.isPending} onClick={(event) => { event.preventDefault(); if (deleteTarget) del.mutate(deleteTarget); }} className="h-[38px] rounded-[9px] bg-[#C76161] px-4 text-[9px] font-semibold text-white hover:bg-[#B65555]">{del.isPending && <Loader2 className="ml-[5px] h-[11px] w-[11px] animate-spin" />}حذف نهائي</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

const FilterStatCard = ({ title, value, helper, icon: Icon, tone }: { title: string; value: number; helper: string; icon: LucideIcon; tone: "indigo" | "green" | "blue" | "coral" }) => {
  const style = {
    indigo: { icon: "bg-[#F1EFFF] text-[#675CBA]", line: "bg-[#675CBA]" },
    green: { icon: "bg-[#EAF7EE] text-[#629067]", line: "bg-[#629067]" },
    blue: { icon: "bg-[#EDF4FF] text-[#5680CF]", line: "bg-[#5680CF]" },
    coral: { icon: "bg-[#FFF0ED] text-[#D06A5E]", line: "bg-[#D06A5E]" },
  }[tone];

  return <article className="relative min-h-[116px] overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white p-[13px]"><span className={cn("absolute inset-x-0 top-0 h-[3px]", style.line)} /><div className={cn("flex h-[32px] w-[32px] items-center justify-center rounded-[10px]", style.icon)}><Icon className="h-[14px] w-[14px]" /></div><p className="mt-[12px] text-[8.5px] text-[#8D949E]">{title}</p><p className="mt-[4px] text-[20px] font-semibold leading-none text-[#303741]">{value.toLocaleString("en-US")}</p><p className="mt-[6px] text-[7px] text-[#A0A6AF]">{helper}</p></article>;
};

const FilterStatus = ({ active }: { active: boolean }) => {
  return <span className={cn("inline-flex h-[24px] items-center gap-[5px] rounded-[7px] border px-[7px] text-[6.5px] font-semibold", active ? "border-[#D8E8DD] bg-[#EFF8F2] text-[#568468]" : "border-[#E3E6EA] bg-[#F5F6F8] text-[#818994]")}><span className={cn("h-[5px] w-[5px] rounded-full", active ? "bg-[#629067]" : "bg-[#969EA8]")} />{active ? "نشط" : "معطل"}</span>;
};

const FormSection = ({ title, icon: Icon, children }: { title: string; icon: LucideIcon; children: ReactNode }) => {
  return <section className="rounded-[14px] border border-[#E5E9EF] bg-white p-[12px]"><div className="mb-[10px] flex items-center gap-[7px] border-b border-[#F0F2F5] pb-[8px]"><div className="flex h-[28px] w-[28px] items-center justify-center rounded-[8px] bg-[#F1EFFF] text-[#675CBA]"><Icon className="h-[11px] w-[11px]" /></div><h3 className="text-[9.5px] font-semibold text-[#4A525C]">{title}</h3></div><div className="space-y-[9px]">{children}</div></section>;
};

const Field = ({ label, children, required = false }: { label: string; children: ReactNode; required?: boolean }) => {
  return <div><Label className="mb-[6px] block text-[8px] font-semibold text-[#727A84]">{label}{required && <span className="mr-[3px] text-[#C76161]">*</span>}</Label>{children}</div>;
};

const EmptyFilters = ({ text }: { text: string }) => {
  return <div className="flex min-h-[230px] flex-col items-center justify-center rounded-[14px] bg-white px-6 text-center"><div className="flex h-[45px] w-[45px] items-center justify-center rounded-[13px] bg-[#F0F2F5] text-[#8C949E]"><FilterIcon className="h-[18px] w-[18px]" /></div><h3 className="mt-3 text-[10px] font-semibold text-[#535B65]">لا توجد فلاتر</h3><p className="mt-[4px] text-[7px] text-[#9BA2AC]">{text}</p></div>;
};

export default AdminBrandFiltersPage;