import { useMemo, useState, type ChangeEvent, type FormEvent, type LucideIcon, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { uploadOptimizedImage } from "@/lib/prepareImageUpload";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { CheckCircle2, CircleOff, FolderTree, Image as ImageIcon, Layers3, Link2, Loader2, Pencil, Plus, Search, Tag, Trash2, Upload, X } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import AdminPageHeader from "@/components/admin/AdminPageHeader";

interface Brand {
  id: string;
  name: string;
  slug: string | null;
  logo_url: string | null;
  hero_image: string | null;
  description: string | null;
  countries: string[] | null;
  is_active: boolean | null;
  sort_order: number | null;
  created_at?: string;
  updated_at?: string;
}

interface Category {
  id: string;
  name_ar: string;
  parent_id: string | null;
}

interface BrandCategoryRow {
  brand_id: string;
  category_id: string;
}

type BrandForm = {
  name: string;
  slug: string;
  logo_url: string;
  hero_image: string;
  description: string;
  countries: string[];
  is_active: boolean;
  sort_order: number;
};

type StatusFilter = "all" | "active" | "inactive";
type LinkFilter = "all" | "linked" | "unlinked";

const SINGLE_COUNTRY = "GLOBAL";

const generateSlug = (text: string) => {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\u0600-\u06FF\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
};

const emptyForm = (): BrandForm => ({
  name: "",
  slug: "",
  logo_url: "",
  hero_image: "",
  description: "",
  countries: [SINGLE_COUNTRY],
  is_active: true,
  sort_order: 0,
});

const AdminBrandsPage = () => {
  const queryClient = useQueryClient();

  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingBrand, setEditingBrand] = useState<Brand | null>(null);
  const [deleteBrand, setDeleteBrand] = useState<Brand | null>(null);

  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [linkFilter, setLinkFilter] = useState<LinkFilter>("all");

  const [formData, setFormData] = useState<BrandForm>(emptyForm());
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [selectedCategoryIds, setSelectedCategoryIds] = useState<string[]>([]);

  const [uploadingLogo, setUploadingLogo] = useState(false);
  const [uploadingHero, setUploadingHero] = useState(false);

  /* =========================================================
     QUERIES
  ========================================================= */

  const { data: brands = [], isLoading, isFetching } = useQuery({
    queryKey: ["admin-brands"],
    queryFn: async () => {
      const { data, error } = await supabase.from("brands").select("id,name,slug,logo_url,hero_image,description,countries,is_active,sort_order,created_at,updated_at").order("sort_order", { ascending: true }).order("name", { ascending: true });

      if (error) throw error;

      return (data || []) as Brand[];
    },
    staleTime: 30_000,
  });

  const { data: categories = [] } = useQuery({
    queryKey: ["admin-categories-for-brands"],
    queryFn: async () => {
      const { data, error } = await supabase.from("categories").select("id,name_ar,parent_id").eq("is_active", true).order("sort_order", { ascending: true });

      if (error) throw error;

      return (data || []) as Category[];
    },
    staleTime: 60_000,
  });

  const { data: brandCategoryRows = [] } = useQuery({
    queryKey: ["admin-brand-categories"],
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("brand_categories").select("brand_id,category_id");

      if (error) throw error;

      return (data || []) as BrandCategoryRow[];
    },
    staleTime: 30_000,
  });

  /* =========================================================
     DERIVED DATA
  ========================================================= */

  const brandToCategoryIds = useMemo(() => {
    return brandCategoryRows.reduce<Record<string, string[]>>((accumulator, row) => {
      if (!accumulator[row.brand_id]) accumulator[row.brand_id] = [];

      accumulator[row.brand_id].push(row.category_id);

      return accumulator;
    }, {});
  }, [brandCategoryRows]);

  const categoryById = useMemo(() => new Map(categories.map((category) => [category.id, category])), [categories]);

  const rootCategories = useMemo(() => categories.filter((category) => !category.parent_id), [categories]);

  const childrenByParent = useMemo(() => {
    const map = new Map<string, Category[]>();

    categories.forEach((category) => {
      if (!category.parent_id) return;

      const current = map.get(category.parent_id) || [];

      current.push(category);
      map.set(category.parent_id, current);
    });

    return map;
  }, [categories]);

  const stats = useMemo(() => {
    const active = brands.filter((brand) => brand.is_active).length;
    const inactive = brands.length - active;
    const linked = brands.filter((brand) => (brandToCategoryIds[brand.id] || []).length > 0).length;

    return {
      total: brands.length,
      active,
      inactive,
      linked,
    };
  }, [brands, brandToCategoryIds]);

  const filteredBrands = useMemo(() => {
    const normalizedSearch = search.trim().toLowerCase();

    return brands.filter((brand) => {
      const linkedCount = (brandToCategoryIds[brand.id] || []).length;

      const matchesSearch = !normalizedSearch || brand.name.toLowerCase().includes(normalizedSearch) || String(brand.slug || "").toLowerCase().includes(normalizedSearch);

      const matchesStatus = statusFilter === "all" || (statusFilter === "active" && Boolean(brand.is_active)) || (statusFilter === "inactive" && !brand.is_active);

      const matchesLink = linkFilter === "all" || (linkFilter === "linked" && linkedCount > 0) || (linkFilter === "unlinked" && linkedCount === 0);

      return matchesSearch && matchesStatus && matchesLink;
    });
  }, [brands, brandToCategoryIds, search, statusFilter, linkFilter]);

  const hasFilters = Boolean(search.trim()) || statusFilter !== "all" || linkFilter !== "all";

  /* =========================================================
     FORM
  ========================================================= */

  const resetForm = () => {
    setFormData(emptyForm());
    setSlugAutoGenerated(true);
    setSelectedCategoryIds([]);
    setEditingBrand(null);
    setIsDialogOpen(false);
  };

  const openCreate = () => {
    setEditingBrand(null);
    setFormData(emptyForm());
    setSlugAutoGenerated(true);
    setSelectedCategoryIds([]);
    setIsDialogOpen(true);
  };

  const handleEdit = (brand: Brand) => {
    setEditingBrand(brand);

    setFormData({
      name: brand.name || "",
      slug: brand.slug || "",
      logo_url: brand.logo_url || "",
      hero_image: brand.hero_image || "",
      description: brand.description || "",
      countries: brand.countries || [SINGLE_COUNTRY],
      is_active: brand.is_active ?? true,
      sort_order: brand.sort_order ?? 0,
    });

    setSlugAutoGenerated(!brand.slug);
    setSelectedCategoryIds(brandToCategoryIds[brand.id] || []);
    setIsDialogOpen(true);
  };

  const handleNameChange = (name: string) => {
    setFormData((current) => ({
      ...current,
      name,
      slug: slugAutoGenerated ? generateSlug(name) : current.slug,
    }));
  };

  const handleSlugChange = (slug: string) => {
    setSlugAutoGenerated(false);

    setFormData((current) => ({
      ...current,
      slug: generateSlug(slug),
    }));
  };

  /* =========================================================
     SAVE
  ========================================================= */

  const saveMutation = useMutation({
    mutationFn: async (payload: BrandForm & { id?: string; category_ids: string[] }) => {
      const name = payload.name.trim();
      const slug = payload.slug.trim() || generateSlug(name);

      if (!name) throw new Error("أدخل اسم الماركة.");
      if (!slug) throw new Error("تعذر إنشاء رابط صالح للماركة.");

      let duplicateQuery = supabase.from("brands").select("id").eq("slug", slug).limit(1);

      if (payload.id) duplicateQuery = duplicateQuery.neq("id", payload.id);

      const { data: duplicatedBrands, error: duplicateError } = await duplicateQuery;

      if (duplicateError) throw duplicateError;

      if ((duplicatedBrands || []).length > 0) {
        throw new Error(`الرابط "${slug}" مستخدم بواسطة ماركة أخرى.`);
      }

      const brandData = {
        name,
        slug,
        logo_url: payload.logo_url || null,
        hero_image: payload.hero_image || null,
        description: payload.description.trim() || null,
        countries: payload.countries,
        is_active: payload.is_active,
        sort_order: Number(payload.sort_order || 0),
      };

      let brandId = payload.id;

      if (payload.id) {
        const { data, error } = await supabase.from("brands").update(brandData).eq("id", payload.id).select("id").single();

        if (error) throw error;

        brandId = data.id;
      } else {
        const { data, error } = await supabase.from("brands").insert(brandData).select("id").single();

        if (error) throw error;

        brandId = data.id;
      }

      if (!brandId) throw new Error("تعذر تحديد معرف الماركة.");

      const currentCategoryIds = payload.id ? brandToCategoryIds[brandId] || [] : [];

      const currentSet = new Set(currentCategoryIds);
      const nextSet = new Set(payload.category_ids);

      const toRemove = currentCategoryIds.filter((categoryId) => !nextSet.has(categoryId));
      const toInsert = payload.category_ids.filter((categoryId) => !currentSet.has(categoryId));

      if (toRemove.length > 0) {
        const { error } = await (supabase as any).from("brand_categories").delete().eq("brand_id", brandId).in("category_id", toRemove);

        if (error) throw error;
      }

      if (toInsert.length > 0) {
        const { error } = await (supabase as any).from("brand_categories").insert(toInsert.map((categoryId) => ({ brand_id: brandId, category_id: categoryId })));

        if (error) throw error;
      }
    },

    onSuccess: async () => {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["admin-brands"] }),
        queryClient.invalidateQueries({ queryKey: ["admin-brand-categories"] }),
      ]);

      toast({
        title: editingBrand ? "تم تحديث الماركة" : "تم إضافة الماركة",
        description: editingBrand ? "تم حفظ معلومات الماركة وروابط الأقسام." : "تم إنشاء الماركة وربطها بالأقسام المحددة.",
      });

      resetForm();
    },

    onError: (error: any) => {
      console.error("Brand save error:", error);

      toast({
        title: "تعذر حفظ الماركة",
        description: error?.message || "حدث خطأ أثناء حفظ البيانات.",
        variant: "destructive",
      });
    },
  });

  /* =========================================================
     ACTIVE
  ========================================================= */

  const toggleActiveMutation = useMutation({
    mutationFn: async ({ id, is_active }: { id: string; is_active: boolean }) => {
      const { error } = await supabase.from("brands").update({ is_active }).eq("id", id);

      if (error) throw error;

      return { id, is_active };
    },

    onMutate: async ({ id, is_active }) => {
      await queryClient.cancelQueries({ queryKey: ["admin-brands"] });

      const previous = queryClient.getQueryData<Brand[]>(["admin-brands"]);

      queryClient.setQueryData<Brand[]>(["admin-brands"], (current = []) => current.map((brand) => brand.id === id ? { ...brand, is_active } : brand));

      return { previous };
    },

    onError: (error: any, _variables, context) => {
      if (context?.previous) queryClient.setQueryData(["admin-brands"], context.previous);

      toast({
        title: "تعذر تحديث الحالة",
        description: error?.message || "حدث خطأ أثناء تحديث الماركة.",
        variant: "destructive",
      });
    },

    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ["admin-brands"] });
    },
  });

  /* =========================================================
     DELETE
  ========================================================= */

  const deleteMutation = useMutation({
    mutationFn: async (brand: Brand) => {
      const [{ count: brandIdCount, error: brandIdError }, { count: brandNameCount, error: brandNameError }] = await Promise.all([
        supabase.from("products").select("id", { count: "exact", head: true }).eq("brand_id", brand.id),
        supabase.from("products").select("id", { count: "exact", head: true }).eq("brand", brand.name),
      ]);

      if (brandIdError) throw brandIdError;
      if (brandNameError) throw brandNameError;

      if (Number(brandIdCount || 0) > 0 || Number(brandNameCount || 0) > 0) {
        throw new Error("لا يمكن حذف هذه الماركة لأنها مرتبطة بمنتجات. انقل المنتجات إلى ماركة أخرى أو أزل الربط أولًا.");
      }

      const { error: categoryLinksError } = await (supabase as any).from("brand_categories").delete().eq("brand_id", brand.id);

      if (categoryLinksError) throw categoryLinksError;

      const { error } = await supabase.from("brands").delete().eq("id", brand.id);

      if (error) throw error;
    },

    onSuccess: async () => {
      setDeleteBrand(null);

      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["admin-brands"] }),
        queryClient.invalidateQueries({ queryKey: ["admin-brand-categories"] }),
      ]);

      toast({
        title: "تم حذف الماركة",
        description: "تم حذف الماركة وروابط أقسامها.",
      });
    },

    onError: (error: any) => {
      toast({
        title: "تعذر حذف الماركة",
        description: error?.message || "حدث خطأ أثناء حذف الماركة.",
        variant: "destructive",
      });
    },
  });

  /* =========================================================
     UPLOAD
  ========================================================= */

  const handleImageUpload = async (event: ChangeEvent<HTMLInputElement>, type: "logo" | "hero") => {
    const file = event.target.files?.[0];

    if (!file) return;

    const isLogo = type === "logo";

    if (isLogo) setUploadingLogo(true);
    else setUploadingHero(true);

    try {
      const imageUrl = await uploadOptimizedImage(file, "brands", {
        maxSizeMB: isLogo ? 0.35 : 0.7,
        maxWidthOrHeight: isLogo ? 900 : 1800,
      });

      setFormData((current) => ({
        ...current,
        [isLogo ? "logo_url" : "hero_image"]: imageUrl,
      }));

      toast({
        title: isLogo ? "تم رفع الشعار" : "تم رفع صورة الغلاف",
      });
    } catch (error: any) {
      console.error("Brand image upload error:", error);

      toast({
        title: "فشل رفع الصورة",
        description: error?.message || "تعذر معالجة الصورة.",
        variant: "destructive",
      });
    } finally {
      if (isLogo) setUploadingLogo(false);
      else setUploadingHero(false);

      event.target.value = "";
    }
  };

  /* =========================================================
     CATEGORIES
  ========================================================= */

  const toggleCategory = (categoryId: string, checked: boolean) => {
    setSelectedCategoryIds((current) => {
      if (checked) {
        if (current.includes(categoryId)) return current;

        return [...current, categoryId];
      }

      return current.filter((id) => id !== categoryId);
    });
  };

  const selectAllCategories = () => {
    setSelectedCategoryIds(categories.map((category) => category.id));
  };

  const clearCategories = () => {
    setSelectedCategoryIds([]);
  };

  /* =========================================================
     SUBMIT
  ========================================================= */

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();

    saveMutation.mutate({
      ...formData,
      id: editingBrand?.id,
      category_ids: selectedCategoryIds,
    });
  };

  const clearFilters = () => {
    setSearch("");
    setStatusFilter("all");
    setLinkFilter("all");
  };

  /* =========================================================
     LOADING
  ========================================================= */

  if (isLoading) {
    return (
      <div className="flex min-h-[430px] items-center justify-center">
        <div className="text-center">
          <div className="mx-auto flex h-[48px] w-[48px] items-center justify-center rounded-[14px] border border-[#E5E9EF] bg-white">
            <Loader2 className="h-[18px] w-[18px] animate-spin text-[#675CBA]" />
          </div>

          <p className="mt-3 text-[8px] font-medium text-[#969DA7]">جاري تحميل الماركات...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full space-y-4" dir="rtl">
      {/* =====================================================
          HEADER
      ===================================================== */}

      <AdminPageHeader category="الكتالوج والمخزون" title="إدارة الماركات" description={`${stats.total.toLocaleString("ar-EG")} ماركة مسجلة في المتجر`} actions={[{ label: "إضافة ماركة", icon: Plus, onClick: openCreate, variant: "primary" }]} />

      {/* =====================================================
          STATS
      ===================================================== */}

      <section className="grid grid-cols-2 gap-[9px] lg:grid-cols-4">
        <BrandStatCard title="إجمالي الماركات" value={stats.total} helper="جميع الماركات المسجلة" icon={Tag} tone="indigo" />
        <BrandStatCard title="الماركات النشطة" value={stats.active} helper={`${stats.inactive} ماركة معطلة`} icon={CheckCircle2} tone="green" />
        <BrandStatCard title="مرتبطة بأقسام" value={stats.linked} helper={`${stats.total - stats.linked} بدون ربط`} icon={Layers3} tone="blue" />
        <BrandStatCard title="الماركات المعطلة" value={stats.inactive} helper="لا تظهر حاليًا للعملاء" icon={CircleOff} tone="coral" />
      </section>

      {/* =====================================================
          FILTERS
      ===================================================== */}

      <section className="overflow-hidden rounded-[16px] border border-[#E5E9EF] bg-white">
        <div className="flex items-center justify-between border-b border-[#EDF0F3] px-[14px] py-[11px]">
          <div className="flex items-center gap-[8px]">
            <div className="flex h-[30px] w-[30px] items-center justify-center rounded-[9px] bg-[#F1EFFF] text-[#675CBA]">
              <Search className="h-[13px] w-[13px]" strokeWidth={1.8} />
            </div>

            <div>
              <p className="text-[10px] font-semibold text-[#444B55]">البحث والتصفية</p>
              <p className="mt-[2px] text-[7px] text-[#9BA2AC]">ابحث عن الماركة أو الرابط وراجع ربط الأقسام</p>
            </div>
          </div>

          {hasFilters && (
            <button type="button" onClick={clearFilters} className="flex h-[29px] items-center gap-[5px] rounded-[8px] px-[8px] text-[8px] font-semibold text-[#8A919B] transition-colors hover:bg-[#F5F7F9] hover:text-[#555D68]">
              <X className="h-[10px] w-[10px]" />
              مسح الفلاتر
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 gap-[7px] p-[12px] lg:grid-cols-[minmax(0,1fr)_170px_180px]">
          <div className="relative">
            <Search className="pointer-events-none absolute right-[12px] top-1/2 h-[13px] w-[13px] -translate-y-1/2 text-[#969EA8]" strokeWidth={1.7} />

            <Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="اسم الماركة أو slug..." className="h-[40px] rounded-[10px] border-[#E3E7EC] bg-[#F8FAFC] pr-[35px] pl-[34px] text-[10px] font-medium shadow-none placeholder:text-[#A4ABB4] focus-visible:bg-white focus-visible:ring-0" />

            {search && (
              <button type="button" onClick={() => setSearch("")} className="absolute left-[8px] top-1/2 flex h-[24px] w-[24px] -translate-y-1/2 items-center justify-center rounded-[7px] text-[#9AA1AB] hover:bg-white hover:text-[#5C6470]">
                <X className="h-[11px] w-[11px]" />
              </button>
            )}
          </div>

          <Select value={statusFilter} onValueChange={(value) => setStatusFilter(value as StatusFilter)}>
            <SelectTrigger className="h-[40px] rounded-[10px] border-[#E3E7EC] bg-[#F8FAFC] text-[9px] shadow-none focus:ring-0">
              <SelectValue />
            </SelectTrigger>

            <SelectContent>
              <SelectItem value="all">كل الحالات</SelectItem>
              <SelectItem value="active">نشطة</SelectItem>
              <SelectItem value="inactive">معطلة</SelectItem>
            </SelectContent>
          </Select>

          <Select value={linkFilter} onValueChange={(value) => setLinkFilter(value as LinkFilter)}>
            <SelectTrigger className="h-[40px] rounded-[10px] border-[#E3E7EC] bg-[#F8FAFC] text-[9px] shadow-none focus:ring-0">
              <SelectValue />
            </SelectTrigger>

            <SelectContent>
              <SelectItem value="all">كل روابط الأقسام</SelectItem>
              <SelectItem value="linked">مرتبطة بأقسام</SelectItem>
              <SelectItem value="unlinked">بدون أقسام</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </section>

      {/* =====================================================
          MOBILE
      ===================================================== */}

      <section className="space-y-[8px] md:hidden">
        {filteredBrands.length === 0 ? (
          <BrandsEmpty />
        ) : (
          filteredBrands.map((brand) => (
            <article key={brand.id} className="overflow-hidden rounded-[14px] border border-[#E5E9EF] bg-white">
              <div className="p-[11px]">
                <div className="flex gap-[10px]">
                  <BrandLogo brand={brand} size="mobile" />

                  <div className="min-w-0 flex-1">
                    <div className="flex items-start justify-between gap-[7px]">
                      <div className="min-w-0">
                        <h3 className="truncate text-[11px] font-semibold text-[#3B424C]">{brand.name}</h3>
                        <p dir="ltr" className="mt-[3px] truncate text-right text-[7px] text-[#9299A3]">{brand.slug || "بدون رابط"}</p>
                      </div>

                      <BrandStatus active={Boolean(brand.is_active)} />
                    </div>

                    <div className="mt-[9px] flex flex-wrap gap-[5px]">
                      <span className="rounded-[6px] bg-[#EDF4FF] px-[6px] py-[3px] text-[6px] font-semibold text-[#567BC5]">{(brandToCategoryIds[brand.id] || []).length} أقسام</span>

                      <span className="rounded-[6px] bg-[#F2F4F7] px-[6px] py-[3px] text-[6px] font-semibold text-[#757D87]">الترتيب #{brand.sort_order ?? 0}</span>

                      {!brand.slug && <span className="rounded-[6px] bg-[#FFF5E5] px-[6px] py-[3px] text-[6px] font-semibold text-[#A9782F]">يحتاج رابط</span>}
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-[1fr_1fr_38px] gap-[5px] border-t border-[#EDF0F3] bg-[#FAFBFC] p-[7px]">
                <button type="button" onClick={() => toggleActiveMutation.mutate({ id: brand.id, is_active: !brand.is_active })} className="flex h-[34px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[8px] font-semibold text-[#68717B]">
                  {brand.is_active ? "تعطيل" : "تفعيل"}
                </button>

                <button type="button" onClick={() => handleEdit(brand)} className="flex h-[34px] items-center justify-center gap-[5px] rounded-[8px] border border-[#E3E7EC] bg-white text-[8px] font-semibold text-[#68717B]">
                  <Pencil className="h-[10px] w-[10px]" />
                  تعديل
                </button>

                <button type="button" onClick={() => setDeleteBrand(brand)} className="flex h-[34px] w-[38px] items-center justify-center rounded-[8px] border border-[#F0D7D4] bg-white text-[#C15F56]">
                  <Trash2 className="h-[11px] w-[11px]" />
                </button>
              </div>
            </article>
          ))
        )}
      </section>

      {/* =====================================================
          DESKTOP TABLE
      ===================================================== */}

      <section className="hidden overflow-hidden rounded-[16px] border border-[#E5E9EF] bg-white md:block">
        <div className="flex items-center justify-between border-b border-[#EAEDF1] px-[14px] py-[11px]">
          <div>
            <div className="flex items-center gap-[7px]">
              <Tag className="h-[13px] w-[13px] text-[#675CBA]" strokeWidth={1.8} />
              <h2 className="text-[10px] font-semibold text-[#454C56]">دليل الماركات</h2>
            </div>

            <p className="mt-[4px] text-[7px] text-[#9CA3AC]">{filteredBrands.length.toLocaleString("ar-EG")} نتيجة ظاهرة</p>
          </div>

          {isFetching && (
            <span className="flex items-center gap-[5px] text-[7px] text-[#969DA7]">
              <Loader2 className="h-[10px] w-[10px] animate-spin" />
              تحديث...
            </span>
          )}
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[940px]">
            <thead>
              <tr className="h-[42px] border-b border-[#EAEDF1] bg-[#FAFBFC] text-[7.5px] font-semibold text-[#9299A3]">
                <th className="w-[72px] px-[10px] text-right font-semibold">الشعار</th>
                <th className="px-[10px] text-right font-semibold">الماركة</th>
                <th className="px-[10px] text-right font-semibold">الرابط</th>
                <th className="px-[10px] text-right font-semibold">الأقسام</th>
                <th className="px-[10px] text-right font-semibold">الترتيب</th>
                <th className="px-[10px] text-right font-semibold">الحالة</th>
                <th className="w-[110px] px-[10px] text-center font-semibold">الإجراءات</th>
              </tr>
            </thead>

            <tbody>
              {filteredBrands.length === 0 ? (
                <tr>
                  <td colSpan={7}>
                    <BrandsEmpty />
                  </td>
                </tr>
              ) : (
                filteredBrands.map((brand) => {
                  const linkedCategoryIds = brandToCategoryIds[brand.id] || [];
                  const linkedNames = linkedCategoryIds.map((categoryId) => categoryById.get(categoryId)?.name_ar).filter(Boolean) as string[];

                  return (
                    <tr key={brand.id} className="h-[67px] border-b border-[#F0F2F5] transition-colors last:border-b-0 hover:bg-[#FCFDFE]">
                      <td className="px-[10px]">
                        <BrandLogo brand={brand} size="desktop" />
                      </td>

                      <td className="px-[10px]">
                        <div className="min-w-[180px]">
                          <p className="max-w-[220px] truncate text-[10px] font-semibold text-[#414953]">{brand.name}</p>

                          {brand.description && <p className="mt-[4px] max-w-[230px] truncate text-[6.5px] text-[#9BA2AC]">{brand.description}</p>}
                        </div>
                      </td>

                      <td className="px-[10px]">
                        {brand.slug ? (
                          <div className="flex items-center gap-[5px]">
                            <Link2 className="h-[9px] w-[9px] shrink-0 text-[#9AA1AB]" />
                            <span dir="ltr" className="block max-w-[160px] truncate text-right text-[7.5px] font-medium text-[#737C87]">/brands/{brand.slug}</span>
                          </div>
                        ) : (
                          <span className="rounded-[6px] bg-[#FFF5E5] px-[6px] py-[3px] text-[6px] font-semibold text-[#A9782F]">بدون رابط</span>
                        )}
                      </td>

                      <td className="px-[10px]">
                        <div>
                          <span className={cn("inline-flex h-[25px] items-center gap-[5px] rounded-[7px] border px-[7px] text-[6.5px] font-semibold", linkedCategoryIds.length > 0 ? "border-[#DCE7F4] bg-[#F1F6FC] text-[#5679A4]" : "border-[#E4E7EB] bg-[#F5F6F8] text-[#858D97]")}>
                            <Layers3 className="h-[8px] w-[8px]" />
                            {linkedCategoryIds.length} أقسام
                          </span>

                          {linkedNames.length > 0 && <p className="mt-[4px] max-w-[200px] truncate text-[6px] text-[#A0A6AF]">{linkedNames.slice(0, 3).join("، ")}</p>}
                        </div>
                      </td>

                      <td className="px-[10px]">
                        <span className="inline-flex h-[25px] min-w-[28px] items-center justify-center rounded-[7px] bg-[#F2F4F7] px-[7px] text-[7px] font-semibold text-[#727A84]">{brand.sort_order ?? 0}</span>
                      </td>

                      <td className="px-[10px]">
                        <div className="flex items-center gap-[8px]">
                          <Switch checked={brand.is_active ?? true} onCheckedChange={(checked) => toggleActiveMutation.mutate({ id: brand.id, is_active: checked })} />
                          <span className={cn("text-[7px] font-semibold", brand.is_active ? "text-[#568468]" : "text-[#8B929C]")}>{brand.is_active ? "نشط" : "معطل"}</span>
                        </div>
                      </td>

                      <td className="px-[10px]">
                        <div className="flex items-center justify-center gap-[4px]">
                          <button type="button" title="تعديل الماركة" onClick={() => handleEdit(brand)} className="flex h-[30px] w-[30px] items-center justify-center rounded-[8px] border border-[#E3E7EC] bg-white text-[#707884] transition-colors hover:bg-[#F5F3FF] hover:text-[#675CBA]">
                            <Pencil className="h-[11px] w-[11px]" />
                          </button>

                          <button type="button" title="حذف الماركة" onClick={() => setDeleteBrand(brand)} className="flex h-[30px] w-[30px] items-center justify-center rounded-[8px] border border-[#F0D7D4] bg-white text-[#C15F56] transition-colors hover:bg-[#FFF3F1]">
                            <Trash2 className="h-[11px] w-[11px]" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </section>

      {/* =====================================================
          EDITOR
      ===================================================== */}

      <Dialog open={isDialogOpen} onOpenChange={(open) => { if (!open) resetForm(); else setIsDialogOpen(true); }}>
        <DialogContent dir="rtl" className="max-h-[92vh] max-w-[880px] overflow-y-auto rounded-[18px] border-[#E4E8ED] bg-[#F7F8FA] p-0">
          <DialogHeader className="sticky top-0 z-20 border-b border-[#E6E9EE] bg-white px-5 py-4">
            <div className="flex items-center gap-[10px]">
              <div className="flex h-[36px] w-[36px] items-center justify-center rounded-[11px] bg-[#F1EFFF] text-[#675CBA]">
                {editingBrand ? <Pencil className="h-[15px] w-[15px]" /> : <Plus className="h-[15px] w-[15px]" />}
              </div>

              <div>
                <DialogTitle className="text-right text-[14px] font-semibold text-[#343B45]">{editingBrand ? "تعديل الماركة" : "إضافة ماركة جديدة"}</DialogTitle>

                <DialogDescription className="mt-[3px] text-right text-[8px] text-[#9299A3]">إدارة الهوية المرئية، رابط الماركة، الأقسام المرتبطة وحالة الظهور.</DialogDescription>
              </div>
            </div>
          </DialogHeader>

          <form onSubmit={handleSubmit}>
            <div className="space-y-[10px] p-[10px]">
              <div className="grid grid-cols-1 gap-[10px] lg:grid-cols-[minmax(0,1fr)_270px]">
                {/* BASIC */}

                <div className="space-y-[10px]">
                  <FormSection icon={Tag} title="معلومات الماركة">
                    <Field label="اسم الماركة" required>
                      <Input value={formData.name} onChange={(event) => handleNameChange(event.target.value)} placeholder="مثال: ROLEX" className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" required />
                    </Field>

                    <Field label="الرابط" required>
                      <div className="relative">
                        <span dir="ltr" className="absolute left-[10px] top-1/2 -translate-y-1/2 text-[6.5px] text-[#A0A6AF]">/brands/</span>

                        <Input value={formData.slug} onChange={(event) => handleSlugChange(event.target.value)} placeholder="rolex" dir="ltr" className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] pl-[58px] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" required />
                      </div>

                      <p className="mt-[5px] text-[6px] text-[#A0A6AF]">الرابط النهائي: /brands/{formData.slug || "..."}</p>
                    </Field>

                    <Field label="وصف الماركة">
                      <Textarea value={formData.description} onChange={(event) => setFormData((current) => ({ ...current, description: event.target.value }))} rows={4} placeholder="نبذة قصيرة عن الماركة..." className="resize-none rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] leading-5 shadow-none focus-visible:bg-white focus-visible:ring-0" />
                    </Field>
                  </FormSection>

                  <FormSection icon={FolderTree} title="التنظيم والظهور">
                    <div className="grid grid-cols-1 gap-[9px] sm:grid-cols-2">
                      <Field label="ترتيب العرض">
                        <Input type="number" min={0} value={formData.sort_order} onChange={(event) => setFormData((current) => ({ ...current, sort_order: Number.parseInt(event.target.value, 10) || 0 }))} className="h-[40px] rounded-[9px] border-[#E2E6EB] bg-[#F8FAFC] text-[9px] shadow-none focus-visible:bg-white focus-visible:ring-0" />
                      </Field>

                      <div className="flex min-h-[64px] items-center justify-between rounded-[10px] border border-[#E6E9EE] bg-[#FAFBFC] px-[10px]">
                        <div>
                          <p className="text-[8px] font-semibold text-[#555D67]">حالة الماركة</p>
                          <p className="mt-[2px] text-[6px] text-[#9BA2AC]">{formData.is_active ? "تظهر حاليًا في المتجر" : "مخفية عن العملاء"}</p>
                        </div>

                        <Switch checked={formData.is_active} onCheckedChange={(checked) => setFormData((current) => ({ ...current, is_active: checked }))} />
                      </div>
                    </div>
                  </FormSection>
                </div>

                {/* MEDIA */}

                <div className="space-y-[10px] lg:sticky lg:top-[84px] lg:self-start">
                  <FormSection icon={ImageIcon} title="شعار الماركة">
                    <MediaUploader value={formData.logo_url} loading={uploadingLogo} type="logo" label="رفع شعار" onRemove={() => setFormData((current) => ({ ...current, logo_url: "" }))} onUpload={(event) => void handleImageUpload(event, "logo")} />
                  </FormSection>

                  <FormSection icon={ImageIcon} title="صورة غلاف الماركة">
                    <MediaUploader value={formData.hero_image} loading={uploadingHero} type="hero" label="رفع صورة الغلاف" onRemove={() => setFormData((current) => ({ ...current, hero_image: "" }))} onUpload={(event) => void handleImageUpload(event, "hero")} />
                  </FormSection>
                </div>
              </div>

              {/* CATEGORIES */}

              <FormSection icon={Layers3} title="الأقسام المرتبطة">
                <div className="mb-[9px] flex flex-wrap items-center justify-between gap-[8px]">
                  <div>
                    <p className="text-[7.5px] text-[#7E8690]">تم اختيار <span className="font-semibold text-[#675CBA]">{selectedCategoryIds.length}</span> من {categories.length} قسم</p>
                    <p className="mt-[2px] text-[6px] text-[#A0A6AF]">يحدد الربط الأقسام التي تظهر فيها الماركة للعميل.</p>
                  </div>

                  <div className="flex gap-[5px]">
                    <button type="button" onClick={selectAllCategories} className="h-[29px] rounded-[7px] border border-[#E2E6EB] bg-white px-[8px] text-[6.5px] font-semibold text-[#6E7680] hover:bg-[#F8FAFC]">تحديد الكل</button>

                    <button type="button" onClick={clearCategories} className="h-[29px] rounded-[7px] border border-[#E2E6EB] bg-white px-[8px] text-[6.5px] font-semibold text-[#878E97] hover:bg-[#F8FAFC]">إلغاء الكل</button>
                  </div>
                </div>

                <div className="max-h-[310px] space-y-[7px] overflow-y-auto rounded-[11px] border border-[#E7EAEF] bg-[#FAFBFC] p-[7px]">
                  {rootCategories.map((root) => {
                    const children = childrenByParent.get(root.id) || [];

                    return (
                      <div key={root.id} className="overflow-hidden rounded-[9px] border border-[#E5E9EF] bg-white">
                        <CategoryCheckbox category={root} parentName={null} checked={selectedCategoryIds.includes(root.id)} onChange={(checked) => toggleCategory(root.id, checked)} />

                        {children.length > 0 && (
                          <div className="border-t border-[#F0F2F5] bg-[#FBFCFD] py-[3px] pr-[18px]">
                            {children.map((child) => (
                              <CategoryCheckbox key={child.id} category={child} parentName={root.name_ar} checked={selectedCategoryIds.includes(child.id)} onChange={(checked) => toggleCategory(child.id, checked)} child />
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}

                  {categories.length === 0 && <p className="py-8 text-center text-[7px] text-[#9BA2AC]">لا توجد أقسام نشطة حاليًا.</p>}
                </div>
              </FormSection>
            </div>

            {/* FOOTER */}

            <div className="sticky bottom-0 z-20 flex items-center justify-between gap-3 border-t border-[#E5E9EF] bg-white/95 px-5 py-3 backdrop-blur">
              <p className="hidden text-[6.5px] text-[#A0A6AF] sm:block">{editingBrand ? "سيتم تحديث معلومات الماركة وروابطها." : "سيتم إنشاء الماركة داخل كتالوج Flamingo Park."}</p>

              <div className="mr-auto flex items-center gap-[7px]">
                <Button type="button" variant="outline" disabled={saveMutation.isPending} onClick={resetForm} className="h-[36px] rounded-[9px] border-[#E1E5EA] bg-white px-4 text-[8px] font-semibold text-[#707883] shadow-none">إلغاء</Button>

                <Button type="submit" disabled={saveMutation.isPending || uploadingLogo || uploadingHero} className="h-[36px] rounded-[9px] bg-[#675CBA] px-5 text-[8px] font-semibold text-white shadow-none hover:bg-[#594FAB]">
                  {saveMutation.isPending ? <Loader2 className="ml-[5px] h-[11px] w-[11px] animate-spin" /> : editingBrand ? <Pencil className="ml-[5px] h-[11px] w-[11px]" /> : <Plus className="ml-[5px] h-[11px] w-[11px]" />}
                  {editingBrand ? "حفظ التعديلات" : "إضافة الماركة"}
                </Button>
              </div>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      {/* =====================================================
          DELETE
      ===================================================== */}

      <AlertDialog open={Boolean(deleteBrand)} onOpenChange={(open) => { if (!open) setDeleteBrand(null); }}>
        <AlertDialogContent dir="rtl" className="max-w-[420px] rounded-[15px] border-[#E4E8ED] bg-white p-5">
          <AlertDialogHeader>
            <div className="mb-2 flex h-[38px] w-[38px] items-center justify-center rounded-[11px] bg-[#FFF0F0] text-[#C76161]">
              <Trash2 className="h-[16px] w-[16px]" />
            </div>

            <AlertDialogTitle className="text-[15px] font-semibold text-[#343A44]">حذف الماركة</AlertDialogTitle>

            <AlertDialogDescription className="text-[10px] leading-6 text-[#858D97]">
              سيتم حذف الماركة "{deleteBrand?.name || ""}" وروابطها بالأقسام. إذا كانت مرتبطة بمنتجات فسيتم منع الحذف لحماية بيانات الكتالوج.
            </AlertDialogDescription>
          </AlertDialogHeader>

          <AlertDialogFooter className="mt-2 gap-2">
            <AlertDialogCancel className="h-[38px] rounded-[9px] border-[#E2E6EB] bg-white px-4 text-[9px] font-semibold text-[#6B737E]">إلغاء</AlertDialogCancel>

            <AlertDialogAction className="h-[38px] rounded-[9px] bg-[#C76161] px-4 text-[9px] font-semibold text-white hover:bg-[#B65555]" disabled={deleteMutation.isPending} onClick={(event) => {
              event.preventDefault();

              if (!deleteBrand) return;

              deleteMutation.mutate(deleteBrand);
            }}>
              {deleteMutation.isPending ? <Loader2 className="ml-[5px] h-[12px] w-[12px] animate-spin" /> : <Trash2 className="ml-[5px] h-[12px] w-[12px]" />}
              حذف نهائي
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

/* =========================================================
   STAT
========================================================= */

const BrandStatCard = ({ title, value, helper, icon: Icon, tone }: { title: string; value: number; helper: string; icon: LucideIcon; tone: "indigo" | "green" | "blue" | "coral" }) => {
  const style = {
    indigo: { icon: "bg-[#F1EFFF] text-[#675CBA]", line: "bg-[#675CBA]" },
    green: { icon: "bg-[#EAF7EE] text-[#629067]", line: "bg-[#629067]" },
    blue: { icon: "bg-[#EDF4FF] text-[#5680CF]", line: "bg-[#5680CF]" },
    coral: { icon: "bg-[#FFF0ED] text-[#D06A5E]", line: "bg-[#D06A5E]" },
  }[tone];

  return (
    <article className="relative min-h-[116px] overflow-hidden rounded-[15px] border border-[#E5E9EF] bg-white p-[13px]">
      <span className={cn("absolute inset-x-0 top-0 h-[3px]", style.line)} />

      <div className={cn("flex h-[32px] w-[32px] items-center justify-center rounded-[10px]", style.icon)}>
        <Icon className="h-[14px] w-[14px]" strokeWidth={1.7} />
      </div>

      <p className="mt-[12px] text-[8px] font-medium text-[#8D949E]">{title}</p>
      <p dir="ltr" className="mt-[4px] text-right text-[20px] font-semibold leading-none tracking-[-0.035em] text-[#303741]">{value.toLocaleString("en-US")}</p>
      <p className="mt-[5px] text-[6.5px] text-[#A0A6AF]">{helper}</p>
    </article>
  );
};

/* =========================================================
   LOGO
========================================================= */

const BrandLogo = ({ brand, size }: { brand: Brand; size: "mobile" | "desktop" }) => {
  const box = size === "mobile" ? "h-[68px] w-[68px] rounded-[11px] p-[10px]" : "h-[48px] w-[48px] rounded-[9px] p-[7px]";

  if (!brand.logo_url) {
    return (
      <div className={cn("flex shrink-0 items-center justify-center border border-[#E8EBEF] bg-[#F3F5F7] text-[#969EA8]", box)}>
        <Tag className="h-[15px] w-[15px]" />
      </div>
    );
  }

  return (
    <div className={cn("shrink-0 overflow-hidden border border-[#E8EBEF] bg-white", box)}>
      <img src={brand.logo_url} loading="lazy" decoding="async" alt={brand.name} className="h-full w-full object-contain" />
    </div>
  );
};

/* =========================================================
   STATUS
========================================================= */

const BrandStatus = ({ active }: { active: boolean }) => {
  return (
    <span className={cn("inline-flex h-[24px] items-center gap-[5px] rounded-[7px] border px-[7px] text-[6.5px] font-semibold", active ? "border-[#D8E8DD] bg-[#EFF8F2] text-[#568468]" : "border-[#E3E6EA] bg-[#F5F6F8] text-[#818994]")}>
      <span className={cn("h-[5px] w-[5px] rounded-full", active ? "bg-[#629067]" : "bg-[#969EA8]")} />
      {active ? "نشط" : "معطل"}
    </span>
  );
};

/* =========================================================
   FORM HELPERS
========================================================= */

const FormSection = ({ icon: Icon, title, children }: { icon: LucideIcon; title: string; children: ReactNode }) => {
  return (
    <section className="rounded-[14px] border border-[#E5E9EF] bg-white p-[12px]">
      <div className="mb-[11px] flex items-center gap-[7px] border-b border-[#F0F2F5] pb-[9px]">
        <div className="flex h-[28px] w-[28px] items-center justify-center rounded-[8px] bg-[#F1EFFF] text-[#675CBA]">
          <Icon className="h-[11px] w-[11px]" />
        </div>

        <h3 className="text-[9px] font-semibold text-[#4A525C]">{title}</h3>
      </div>

      <div className="space-y-[9px]">{children}</div>
    </section>
  );
};

const Field = ({ label, children, required = false }: { label: string; children: ReactNode; required?: boolean }) => {
  return (
    <div>
      <Label className="mb-[6px] block text-[7.5px] font-semibold text-[#727A84]">{label}{required && <span className="mr-[3px] text-[#C76161]">*</span>}</Label>
      {children}
    </div>
  );
};

/* =========================================================
   MEDIA UPLOADER
========================================================= */

const MediaUploader = ({ value, loading, type, label, onRemove, onUpload }: { value: string; loading: boolean; type: "logo" | "hero"; label: string; onRemove: () => void; onUpload: (event: ChangeEvent<HTMLInputElement>) => void }) => {
  const aspect = type === "logo" ? "aspect-square" : "aspect-[16/9]";

  if (value) {
    return (
      <div>
        <div className={cn("relative overflow-hidden rounded-[11px] border border-[#E3E7EC] bg-[#F5F6F8]", aspect)}>
          <img src={value} alt="" className={cn("h-full w-full", type === "logo" ? "object-contain p-[16px]" : "object-cover")} />

          <button type="button" onClick={onRemove} className="absolute left-[7px] top-[7px] flex h-[27px] w-[27px] items-center justify-center rounded-[8px] bg-white/95 text-[#C15F56] shadow-sm">
            <Trash2 className="h-[10px] w-[10px]" />
          </button>
        </div>

        <label className="mt-[6px] flex h-[33px] cursor-pointer items-center justify-center gap-[5px] rounded-[8px] border border-[#E2E6EB] bg-white text-[7px] font-semibold text-[#6F7781] hover:bg-[#F8FAFC]">
          {loading ? <Loader2 className="h-[10px] w-[10px] animate-spin" /> : <Upload className="h-[10px] w-[10px]" />}
          تغيير الصورة
          <input type="file" accept="image/*,.heic,.heif" className="hidden" disabled={loading} onChange={onUpload} />
        </label>
      </div>
    );
  }

  return (
    <label className={cn("flex cursor-pointer flex-col items-center justify-center rounded-[11px] border border-dashed border-[#D9DEE5] bg-[#FAFBFC] transition-colors hover:border-[#BFB8DE] hover:bg-[#F9F8FF]", aspect, loading && "pointer-events-none opacity-70")}>
      {loading ? (
        <>
          <Loader2 className="h-[18px] w-[18px] animate-spin text-[#675CBA]" />
          <span className="mt-2 text-[6.5px] text-[#858D97]">جاري الرفع...</span>
        </>
      ) : (
        <>
          <div className="flex h-[36px] w-[36px] items-center justify-center rounded-[10px] bg-[#F1EFFF] text-[#675CBA]">
            <Upload className="h-[14px] w-[14px]" />
          </div>

          <span className="mt-[7px] text-[7.5px] font-semibold text-[#626A74]">{label}</span>
          <span className="mt-[2px] text-[5.8px] text-[#A0A6AF]">JPG · PNG · WEBP · HEIC</span>
        </>
      )}

      <input type="file" accept="image/*,.heic,.heif" className="hidden" disabled={loading} onChange={onUpload} />
    </label>
  );
};

/* =========================================================
   CATEGORY CHECKBOX
========================================================= */

const CategoryCheckbox = ({ category, parentName, checked, onChange, child = false }: { category: Category; parentName: string | null; checked: boolean; onChange: (checked: boolean) => void; child?: boolean }) => {
  return (
    <label className={cn("flex cursor-pointer items-center gap-[8px] px-[9px] py-[8px] transition-colors hover:bg-[#F8FAFC]", child && "py-[7px]")}>
      <Checkbox checked={checked} onCheckedChange={(value) => onChange(Boolean(value))} className="h-[14px] w-[14px] border-[#BCC2CA] data-[state=checked]:border-[#675CBA] data-[state=checked]:bg-[#675CBA]" />

      <div className="min-w-0 flex-1">
        <p className={cn("truncate font-medium text-[#555D67]", child ? "text-[7px]" : "text-[8px]")}>{category.name_ar}</p>

        {parentName && <p className="mt-[2px] truncate text-[5.8px] text-[#A0A6AF]">{parentName}</p>}
      </div>

      <span className={cn("rounded-[5px] px-[5px] py-[2px] text-[5.5px] font-semibold", child ? "bg-[#EDF4FF] text-[#567BC5]" : "bg-[#F2F0FB] text-[#6D64A5]")}>{child ? "فرعي" : "رئيسي"}</span>
    </label>
  );
};

/* =========================================================
   EMPTY
========================================================= */

const BrandsEmpty = () => {
  return (
    <div className="flex min-h-[230px] flex-col items-center justify-center px-6 text-center">
      <div className="flex h-[45px] w-[45px] items-center justify-center rounded-[13px] bg-[#F0F2F5] text-[#8C949E]">
        <Tag className="h-[18px] w-[18px]" />
      </div>

      <h3 className="mt-3 text-[10px] font-semibold text-[#535B65]">لا توجد ماركات</h3>
      <p className="mt-[4px] text-[7px] text-[#9BA2AC]">لم نجد ماركات مطابقة للبحث والفلاتر الحالية.</p>
    </div>
  );
};

export default AdminBrandsPage;